import{canonical,sha256,exact}from'./attestation.mjs';
import{WIRE}from'./contracts.mjs';
import{REGIA_CORPUS,regiaCorpusDigest}from'./regia_corpus.mjs';
import{buildPlayerBridge,validatePlayerBridge}from'./player_bridge.mjs';
const FORBIDDEN=Object.freeze(['invent_mechanics','invent_outcome','voice_pg','reveal_hidden','invent_object','invent_position']);
const pick=(o,k)=>o&&typeof o==='object'&&Object.hasOwn(o,k)?o[k]:null;
export async function buildBeatPlan(result){
 const s=result.projection,frames=s.dialogue.frames.map(x=>({frame_id:x.frame_id,variant_id:x.variant_id})),personas=s.personas.map(x=>({actor_key:x.actor_key,persona_digest:x.persona_digest,rhythm_profile:x.persona?.rhythm_profile??'owner_default'})),bridge=await buildPlayerBridge(s),corpusSha=await regiaCorpusDigest();
 const beats=[];
 for(const f of s.fact_refs)beats.push({beat_id:`fact:${f.source_id}`,seq:beats.length+1,kind:'fact',fact_refs:[f.source_id],atom_refs:[],player_claim_refs:[],responds_to_player:false,continuity_opening:{authorized_history_refs:[]},physical_consequence:null,posture_recovery:null,trajectory_action:null,authoritative_outcome:{fact_code:f.fact_code,semantic_class:f.semantic_class,digest:f.digest},emotional_reaction:null,allowed_dialogue_act:{personas,frames},spatial_after_state:null,transition_initiative:null,forbidden_claims:FORBIDDEN});
 for(const a of[...s.atoms].sort((x,y)=>x.ordinal-y.ordinal)){const refs=bridge.claims.filter(c=>c.source_atom_ref===a.declaration_ref).map(c=>c.claim_id);beats.push({beat_id:`atom:${a.declaration_ref}`,seq:beats.length+1,kind:'atom',fact_refs:[s.fact_refs[0].source_id],atom_refs:[a.declaration_ref],player_claim_refs:refs,responds_to_player:refs.length>0,continuity_opening:{authorized_history_refs:[]},physical_consequence:pick(a.outcome,'physical_consequence'),posture_recovery:pick(a.outcome,'posture_recovery'),trajectory_action:pick(a.intent,'trajectory')??pick(a.intent,'action'),authoritative_outcome:a.outcome,emotional_reaction:pick(a.outcome,'emotional_reaction'),allowed_dialogue_act:{personas,frames},spatial_after_state:pick(a.outcome,'spatial_after_state'),transition_initiative:pick(a.outcome,'transition_initiative'),forbidden_claims:FORBIDDEN});}
 if(bridge.responds_to_player&&beats.length){beats[0]={...beats[0],player_claim_refs:bridge.claims.map(c=>c.claim_id),responds_to_player:true};}
 const body={schema_version:WIRE.beat_plan,prompt_version:WIRE.prompt,projection_id:result.projection_id,projection_sha256:result.projection_sha256,phase:s.phase,player_bridge:bridge,regia_corpus:REGIA_CORPUS,regia_corpus_sha256:corpusSha,beats,anti_repetition:{within_response:true,authorized_history_refs:[]}};
 return Object.freeze({...body,plan_sha256:await sha256(`${WIRE.beat_plan}\n${canonical(body)}`)});
}
export async function validateBeatPlan(p,result){
 if(!exact(p,['schema_version','prompt_version','projection_id','projection_sha256','phase','player_bridge','regia_corpus','regia_corpus_sha256','beats','anti_repetition','plan_sha256'])||p.schema_version!==WIRE.beat_plan||p.prompt_version!==WIRE.prompt||p.projection_id!==result.projection_id||p.projection_sha256!==result.projection_sha256||!await validatePlayerBridge(p.player_bridge)||p.regia_corpus?.schema_version!=='regia_corpus_v1'||canonical(p.regia_corpus)!==canonical(REGIA_CORPUS)||p.regia_corpus_sha256!==await regiaCorpusDigest()||!Array.isArray(p.beats)||!p.beats.length||!/^[0-9a-f]{64}$/u.test(p.plan_sha256))return'BEAT_PLAN_INVALID';
 const keys=['beat_id','seq','kind','fact_refs','atom_refs','player_claim_refs','responds_to_player','continuity_opening','physical_consequence','posture_recovery','trajectory_action','authoritative_outcome','emotional_reaction','allowed_dialogue_act','spatial_after_state','transition_initiative','forbidden_claims'];
 for(let i=0;i<p.beats.length;i++){const b=p.beats[i];if(!exact(b,keys)||b.seq!==i+1||!['fact','atom'].includes(b.kind)||!b.fact_refs.length||!Array.isArray(b.atom_refs)||!Array.isArray(b.player_claim_refs)||b.responds_to_player!==(b.player_claim_refs.length>0)||b.player_claim_refs.some(x=>!p.player_bridge.claims.some(c=>c.claim_id===x))||!exact(b.continuity_opening,['authorized_history_refs'])||b.continuity_opening.authorized_history_refs.length!==0||!exact(b.allowed_dialogue_act,['personas','frames'])||JSON.stringify(b.forbidden_claims)!==JSON.stringify(FORBIDDEN))return'BEAT_PLAN_INVALID'}if(p.player_bridge.responds_to_player&&(!p.beats[0].responds_to_player||!p.beats[0].player_claim_refs.length))return'BEAT_PLAN_INVALID';const expected=await buildBeatPlan(result);if(canonical(p)!==canonical(expected))return'BEAT_PLAN_SURFACE_BINDING';const{plan_sha256,...body}=p;return plan_sha256===await sha256(`${WIRE.beat_plan}\n${canonical(body)}`)?null:'BEAT_PLAN_DIGEST';
}
export function expectedBeatSegments(plan){return plan.beats.map(b=>({beat_id:b.beat_id,seq:b.seq,fact_refs:b.fact_refs,atom_refs:b.atom_refs,player_claim_refs:b.player_claim_refs,responds_to_player:b.responds_to_player}));}

