import {EXCHANGE,PROVIDER,RPC,WIRE} from './contracts.mjs';
import {canonical,sha256} from './attestation.mjs';
import {deterministicFallback} from './fallback.mjs';
import {renderPlan} from './renderer.mjs';
import {buildProviderRequest} from './prompt.mjs';
import {validateClaimSurfaceBinding,validatePublicRequest,validateSurfaceResult} from './validator.mjs';
import {buildBeatPlan,validateBeatPlan} from './beat_plan.mjs';
const metricsZero=()=>({input_tokens:0,output_tokens:0,reasoning_tokens:0,total_tokens:0});
const params={claim:(t,q,fp)=>({p_worker_token:t,p_master_session:q.master_session_id,p_authority_receipt:q.authority_receipt_id,p_event_kind:q.event_kind,p_renderer_version:WIRE.renderer,p_request_key:q.request_key,p_request_fingerprint:fp}),surface:(t,q)=>({p_worker_token:t,p_master_session_id:q.master_session_id,p_authority_receipt_id:q.authority_receipt_id})};
const rpcFor=q=>EXCHANGE.includes(q.event_kind)?{claim:RPC.exchange_claim,surface:RPC.exchange_surface}:{claim:RPC.claim,surface:RPC.surface};
async function fingerprint(q){return sha256(`mission-request/1.0\n${canonical({master_session_id:q.master_session_id,authority_receipt_id:q.authority_receipt_id,event_kind:q.event_kind,renderer_version:WIRE.renderer})}`)}
async function resultOf(q,claim,realization,source,fp){return {authority_sha256:claim.authority_sha256,contract_version:WIRE.result,master_session_id:q.master_session_id,narration:realization.narration,realization,renderer_version:WIRE.renderer,request_fingerprint:fp,source}}
async function ack(rpc,workerToken,publicationId,deliveryKey){if(!publicationId)return false;try{const x=await rpc.call(RPC.ack,{p_worker_token:workerToken,p_publication:publicationId,p_delivery_key:deliveryKey});return x.status==='delivered'}catch{return false}}
async function expire(rpc,workerToken,receiptId,fallbackResult,fallbackSha){try{return await rpc.call(RPC.expire,{p_worker_token:workerToken,p_receipt:receiptId,p_fallback_result:fallbackResult,p_fallback_sha:fallbackSha})}catch{return null}}
async function publishedResponse(rpc,workerToken,x,request,code='REPLAY'){const result=x.publication?.result;if(!result)return null;let pub=x.publication_id??x.publication?.publication_id;if(!pub&&x.receipt_id){try{const y=await rpc.call(RPC.reconcile,{p_worker_token:workerToken,p_receipt:x.receipt_id,p_fallback_result:null,p_fallback_sha:null});pub=y.publication_id}catch{return {status:202,code:'DELIVERY_ACK_REQUIRED',result}}}const delivered=await ack(rpc,workerToken,pub,request.request_key);return delivered?{status:200,code,result}:{status:202,code:'DELIVERY_ACK_REQUIRED',result}}
export async function run({request,rpc,provider,workerToken}){
 const bad=validatePublicRequest(request);if(bad)return {status:400,code:bad};const selected=rpcFor(request);let fp,claim;try{fp=await fingerprint(request);claim=await rpc.call(selected.claim,params.claim(workerToken,request,fp))}catch(e){return {status:e.status===401||e.status===403?403:409,code:'AUTHORITY_REJECTED'}}
 const replay=await publishedResponse(rpc,workerToken,claim,request);if(replay)return replay;if(!claim.receipt_id||!claim.authority_sha256)return {status:409,code:'CLAIM_INVALID'};
 if(['reserved','authorized','provider_started'].includes(claim.status)){let x;try{x=await rpc.call(RPC.reconcile,{p_worker_token:workerToken,p_receipt:claim.receipt_id,p_fallback_result:null,p_fallback_sha:null})}catch{return {status:202,code:'IN_PROGRESS'}}const pub=await publishedResponse(rpc,workerToken,x,request);if(pub)return pub;if(x.status!=='claimed')return {status:202,code:'IN_PROGRESS'};claim={...claim,status:'claimed'}}
 let surfaceResult,beatPlan;try{surfaceResult=await rpc.call(selected.surface,params.surface(workerToken,request));const e=validateSurfaceResult(surfaceResult,request);if(e)return {status:409,code:e};const b=await validateClaimSurfaceBinding(claim,request,surfaceResult);if(b)return {status:409,code:b};beatPlan=await buildBeatPlan(surfaceResult);if(await validateBeatPlan(beatPlan,surfaceResult))return{status:409,code:'BEAT_PLAN_REJECTED'}}catch{return {status:409,code:'SURFACE_REJECTED'}}
 const fallback=deterministicFallback(surfaceResult,beatPlan),fallbackResult=fallback?await resultOf(request,claim,fallback,'fallback',fp):null,fallbackSha=fallbackResult?await sha256(fallbackResult):null;let reserve;try{reserve=await rpc.call(RPC.reserve,{p_worker_token:workerToken,p_receipt:claim.receipt_id,p_lease_seconds:PROVIDER.lease_seconds,p_fallback_result:fallbackResult,p_fallback_sha:fallbackSha})}catch{await expire(rpc,workerToken,claim.receipt_id,fallbackResult,fallbackSha);return {status:409,code:'RESERVE_REJECTED'}}
 const reservedPub=await publishedResponse(rpc,workerToken,reserve,request,'FALLBACK');if(reservedPub)return reservedPub;if(reserve.status!=='reserved')return {status:503,code:reserve.status==='budget_denied'?'BUDGET_DENIED':'RUNTIME_DISABLED'};
 let authorization,consumed;try{authorization=await rpc.call(RPC.authorize,{p_worker_token:workerToken,p_receipt:claim.receipt_id,p_attempt:reserve.attempt_id,p_lease_token:reserve.lease_token});if(authorization.model!==PROVIDER.model||authorization.reasoning_effort!==PROVIDER.reasoning_effort||authorization.store!==false||!Number.isInteger(authorization.max_output_tokens)||authorization.max_output_tokens<1||authorization.max_output_tokens>PROVIDER.max_output_tokens)throw Error('POLICY_DRIFT');consumed=await rpc.call(RPC.consume,{p_worker_token:workerToken,p_authorization:authorization.authorization_id,p_dispatch_token:authorization.dispatch_token})}catch{await expire(rpc,workerToken,claim.receipt_id,fallbackResult,fallbackSha);return {status:409,code:'PROVIDER_CAS_REJECTED'}}
 let realization,metrics,source='provider';const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),PROVIDER.timeout_ms);try{const out=await provider.create(buildProviderRequest(surfaceResult,beatPlan,ctl.signal,authorization.max_output_tokens));realization=renderPlan(surfaceResult,beatPlan,out.realization);source=realization?'provider':'fallback';if(source==='fallback')realization=fallback;metrics=out.metrics;if(!realization){const x=await expire(rpc,workerToken,claim.receipt_id,null,null),pub=x&&await publishedResponse(rpc,workerToken,x,request,'FALLBACK');return pub??{status:503,code:'OWNER_SEALED_FALLBACK_UNAVAILABLE'}}}catch{const x=await expire(rpc,workerToken,claim.receipt_id,fallbackResult,fallbackSha),pub=x&&await publishedResponse(rpc,workerToken,x,request,'FALLBACK');return pub??{status:202,code:'UNKNOWN_BILLABLE_PENDING'}}finally{clearTimeout(timer)}
 const result=await resultOf(request,claim,realization,source,fp),resultSha=await sha256(result);try{const done=await rpc.call(RPC.finalize,{p_worker_token:workerToken,p_authorization:authorization.authorization_id,p_finalize_token:consumed.finalize_token,p_source:source,p_result:result,p_result_sha:resultSha,p_metrics:metrics??metricsZero()}),pub=await publishedResponse(rpc,workerToken,done,request,source==='provider'?'OK':'FALLBACK');return pub??{status:202,code:'FINALIZE_RECONCILE_REQUIRED'}}catch{const x=await expire(rpc,workerToken,claim.receipt_id,fallbackResult,fallbackSha),pub=x&&await publishedResponse(rpc,workerToken,x,request,'FALLBACK');return pub??{status:202,code:'FINALIZE_RECONCILE_REQUIRED'}}
}

