import {WIRE} from './contracts.mjs';
import {charLength} from './validator.mjs';
import {expectedBeatSegments} from './beat_plan.mjs';
import {semanticGate} from './renderer.mjs';
const ENV=Object.freeze({deposito_cordami:'Il deposito è lungo e stretto. Assi scure, umide al tatto, fiancheggiano scaffali di cordami e un banco da lavoro. La luce serale entra dagli accessi e nell\'aria restano odore di canapa e legno.',percorso_esterno_approdo:'Il percorso corre tra magazzini bassi e pali d\'ormeggio. L\'aria salmastra arriva dall\'approdo e gli spazi tra gli edifici restano esposti alla luce serale.',riparo_esterno_approdo:'Una tettoia di assi, aperta su un lato, sorge presso l\'approdo. Il tetto basso protegge uno spazio essenziale, battuto dall\'aria salmastra.'});
const SCENE=Object.freeze({lettura_ambiente:['Nella scanalatura della rastrelliera resta una fibra azzurra cerata, diversa dai cordami comuni.','Sulla soglia di servizio il fango interrompe la polvere verso l\'esterno; non identifica chi è passato.'],raccolta_tracce:['Nella scanalatura della rastrelliera resta una fibra azzurra cerata, diversa dai cordami comuni.','Sulla soglia di servizio il fango interrompe la polvere verso l\'esterno; non identifica chi è passato.','L\'orario del carico è ripassato sopra una prima scrittura ancora leggibile.'],transizione_inseguimento:['Un breve legaccio azzurro è impigliato basso lungo la rotta compatibile con la porta di servizio.'],incontro_refurtiva:['La cassa mancante è al riparo, ancora riconoscibile e sotto il controllo dei due banditi.'],recupero:['La cassa mancante è al riparo, ancora riconoscibile e sotto il controllo dei due banditi.']});
const MIYO=Object.freeze({briefing_miyo:['Grazie per essere venuti.','Al controllo serale manca una cassa di filati grezzi.','Non conosco identità, rifugio, intenzioni o tattiche di chi ha preso la cassa.'],lettura_ambiente:['Capisco. Non posso aggiungere altro.','Non conosco identità, rifugio, intenzioni o tattiche di chi ha preso la cassa.'],raccolta_tracce:['Capisco. Non posso aggiungere altro.','Non conosco identità, rifugio, intenzioni o tattiche di chi ha preso la cassa.','Mio fratello ha coperto un carico fuori dal proprio orario e teme una sanzione.'],chiusura_miyo:['Sono qui. Raccontatemi cosa è accaduto.','Il carico è tornato al deposito.']});
export function deterministicFallback(result,plan){const s=result.projection;if(s.atoms.length)return null;const units=expectedBeatSegments(plan),sources=[ENV[s.frame.environment_scope],...(SCENE[s.phase]??[]),...(MIYO[s.phase]??[])].filter(Boolean);if(units.length>sources.length||new Set(sources).size!==sources.length)return null;const narration=sources.join(' ');if(charLength(narration)<400||charLength(narration)>3500||!semanticGate(narration,plan))return null;const segments=units.map((u,i)=>({...u,persona_digest:null,rhythm_profile:null,dialogue_frame_id:null,dialogue_variant_id:null,physical_text:sources[i],utterance:null}));return {schema_version:WIRE.realization,prompt_version:WIRE.prompt,projection_id:result.projection_id,projection_sha256:result.projection_sha256,plan_sha256:plan.plan_sha256,regia_corpus_sha256:plan.regia_corpus_sha256,player_bridge_sha256:plan.player_bridge.bridge_sha256,phase:s.phase,segments,narration}}

