import{canonical,sha256,exact}from'./attestation.mjs';
const ALLOW=new Set(['manovra_tentata','postura','bersaglio_dichiarato','gesto_rivolto','registro_emotivo','vincolo_autoimposto','interazione_ambiente','dialogue_intent','battuta']);
const FORBID=/auto_?risoluzione|godmod|damage|danni|metri|contatto_?riuscito|esito|successo|fallimento|ferita|chakra|punti_?vita|ignore\s+(?:le|i|gli)|system\s+prompt|<\/?script/iu;
const quote=/^(?:<([^<>]{1,500})>|«([^«»]{1,500})»|"([^"\n]{1,500})")$/u;
const LICENSE=Object.freeze(['reprise','acknowledge','emotional_response']);
const conditional=/\b(?:tenterei|proverei|cercherei|vorrei|mirerei|tenterebbe|proverebbe|cercherebbe|vorrebbe|mirerebbe|tentasse|provasse|cercasse)\b/iu;
export function utteranceIntent(value){if(typeof value!=='string')return null;const m=value.trim().match(quote);if(!m)return null;const raw=(m[1]??m[2]??m[3]).normalize('NFC').replace(/\s+/gu,' ').trim();if(!raw||FORBID.test(raw))return null;return{intent:'direct_address',attempt_signal:conditional.test(raw),source_digest:null,raw_retained:false,license:LICENSE}}
export async function buildPlayerBridge(surface){const claims=[];for(const a of surface.atoms){for(const[k,v]of Object.entries(a.intent??{})){if(!ALLOW.has(k)||FORBID.test(k)||typeof v==='number')continue;let normalized;if(k==='battuta'||k==='dialogue_intent'){normalized=utteranceIntent(v);if(!normalized)continue;normalized.source_digest=await sha256(String(v).normalize('NFC'));}else if(typeof v==='string'&&!FORBID.test(v))normalized={intent:k,attempt_signal:conditional.test(v),value_digest:await sha256(v.normalize('NFC')),raw_retained:false,license:LICENSE};else if(typeof v==='boolean')normalized={intent:k,attempt_signal:false,asserted:v,raw_retained:false,license:LICENSE};else continue;claims.push({claim_id:`${a.declaration_ref}:${k}`,source_atom_ref:a.declaration_ref,kind:k,status:'non-authoritative',normalized});}}
 const body={schema_version:'player_bridge/1.0',claims,responds_to_player:claims.length>0,source_contract:'surface.atoms.intent',raw_action_text_available:false};return{...body,bridge_sha256:await sha256(`player_bridge/1.0\n${canonical(body)}`)};}
export async function validatePlayerBridge(b){if(!exact(b,['schema_version','claims','responds_to_player','source_contract','raw_action_text_available','bridge_sha256'])||b.schema_version!=='player_bridge/1.0'||b.source_contract!=='surface.atoms.intent'||b.raw_action_text_available!==false||!Array.isArray(b.claims)||b.responds_to_player!==(b.claims.length>0)||!/^[0-9a-f]{64}$/u.test(b.bridge_sha256))return false;for(const c of b.claims){if(!exact(c,['claim_id','source_atom_ref','kind','status','normalized'])||!ALLOW.has(c.kind)||c.status!=='non-authoritative'||typeof c.claim_id!=='string'||typeof c.source_atom_ref!=='string'||!c.normalized||c.normalized.raw_retained!==false||JSON.stringify(c.normalized.license)!==JSON.stringify(LICENSE))return false;const nk=c.kind==='battuta'||c.kind==='dialogue_intent'?['intent','attempt_signal','source_digest','raw_retained','license']:Object.hasOwn(c.normalized,'asserted')?['intent','attempt_signal','asserted','raw_retained','license']:['intent','attempt_signal','value_digest','raw_retained','license'];if(!exact(c.normalized,nk)||c.normalized.intent!==(c.kind==='battuta'||c.kind==='dialogue_intent'?'direct_address':c.kind)||typeof c.normalized.attempt_signal!=='boolean'||(Object.hasOwn(c.normalized,'source_digest')&&!/^[0-9a-f]{64}$/u.test(c.normalized.source_digest))||(Object.hasOwn(c.normalized,'value_digest')&&!/^[0-9a-f]{64}$/u.test(c.normalized.value_digest)))return false;}const{bridge_sha256,...body}=b;return bridge_sha256===await sha256(`player_bridge/1.0\n${canonical(body)}`)}

