import{WIRE,NO_PG_VOICE,NO_TECHNICAL}from'./contracts.mjs';import{expectedBeatSegments}from'./beat_plan.mjs';import{charLength}from'./validator.mjs';
const normalize=s=>s.normalize('NFC').replace(/\s+/gu,' ').trim();
const highRisk=['segreto','nascosto','successo','fallimento','uccide','sviene','morto'];
const autoOutcome=/\b(?:ha\s+vinto|vince|sconfigge|riesce\s+(?:a|nel)|manda\s+(?:al\s+tappeto|ko)|privo\s+di\s+sensi)\b/iu;
const playerVoice=/\b(?:il\s+)?(?:giocatore|player|personaggio\s+giocante|pg)\s+(?:dice|afferma|grida|urla|risponde|pensa|esclama|geme)\b/iu;
const metadata=/(?:^|_)(?:id|ref|digest|sha|seq|ordinal|version)(?:$|_)/iu;
const concepts=k=>/damage|danno|harm/iu.test(k)?['danno','danni','ferita']:/distance|metri?|range/iu.test(k)?['metro','metri','distanza']:/turn|round|durata/iu.test(k)?['turno','turni','round']:[k.replaceAll('_',' ')];
function numericClaims(plan){const out=[];const walk=(v,path=[])=>{if(typeof v==='number'&&Number.isFinite(v)){const key=path.at(-1)??'';if(!metadata.test(key))out.push({value:String(v),concepts:concepts(key)});return}if(Array.isArray(v)){for(const x of v)walk(x,path);return}if(v&&typeof v==='object')for(const[k,x]of Object.entries(v))if(!metadata.test(k))walk(x,[...path,k])};for(const b of plan.beats)for(const k of['physical_consequence','posture_recovery','trajectory_action','authoritative_outcome','emotional_reaction','spatial_after_state','transition_initiative'])walk(b[k],[k]);return out}
function numbersBound(text,plan){const claims=numericClaims(plan),lower=text.toLocaleLowerCase('it');for(const m of text.matchAll(/\d+(?:[.,]\d+)?/gu)){const value=m[0],start=Math.max(0,m.index-32),end=Math.min(lower.length,m.index+value.length+32),context=lower.slice(start,end),ok=claims.some(c=>c.value===value&&c.concepts.some(term=>term&&context.includes(term)));if(!ok)return false}return true}
export function semanticGate(text,plan){if(NO_PG_VOICE.test(text)||playerVoice.test(text)||NO_TECHNICAL.test(text)||!numbersBound(text,plan))return false;const authority=JSON.stringify(plan.beats).toLocaleLowerCase('it');const lower=text.toLocaleLowerCase('it');for(const term of highRisk)if(lower.includes(term)&&!authority.includes(term))return false;if(autoOutcome.test(text)&&!/"(?:success|hit|resolved|defeated)"\s*:\s*true|"esito"\s*:\s*"(?:successo|riuscito)"/u.test(authority))return false;return true}
export function validateBeatRealization(result,plan,r){if(!r||r.schema_version!==WIRE.realization||r.prompt_version!==WIRE.prompt||r.projection_id!==result.projection_id||r.projection_sha256!==result.projection_sha256||r.plan_sha256!==plan.plan_sha256||r.regia_corpus_sha256!==plan.regia_corpus_sha256||r.player_bridge_sha256!==plan.player_bridge.bridge_sha256||r.phase!==plan.phase||!Array.isArray(r.segments))return'BEAT_REALIZATION_INVALID';const e=expectedBeatSegments(plan);if(r.segments.length!==e.length)return'BEAT_REALIZATION_COVERAGE';for(let i=0;i<e.length;i++){const x=r.segments[i],b=plan.beats[i],keys=[...Object.keys(e[i]),'persona_digest','rhythm_profile','dialogue_frame_id','dialogue_variant_id','physical_text','utterance'];if(!x||Object.keys(x).sort().join('|')!==keys.sort().join('|')||JSON.stringify(Object.fromEntries(Object.keys(e[i]).map(k=>[k,x[k]])))!==JSON.stringify(e[i])||typeof x.physical_text!=='string'||!normalize(x.physical_text)||!(x.utterance===null||typeof x.utterance==='string'))return'BEAT_REALIZATION_BINDING';const noVoice=x.persona_digest===null&&x.rhythm_profile===null&&x.dialogue_frame_id===null&&x.dialogue_variant_id===null&&x.utterance===null,allowedPersona=b.allowed_dialogue_act.personas.some(p=>p.persona_digest===x.persona_digest&&p.rhythm_profile===x.rhythm_profile),allowedFrame=b.allowed_dialogue_act.frames.some(f=>f.frame_id===x.dialogue_frame_id&&f.variant_id===x.dialogue_variant_id);if(!noVoice&&!(allowedPersona&&allowedFrame&&typeof x.utterance==='string'&&normalize(x.utterance)&&charLength(normalize(x.utterance))<=plan.regia_corpus.max_codepoints_per_utterance))return'BEAT_DIALOGUE_BINDING';if(x.utterance===null&&!noVoice)return'BEAT_DIALOGUE_BINDING';if(x.responds_to_player&&!normalize(x.physical_text))return'BEAT_PLAYER_RESPONSE_MISSING'}return null}
export function renderPlan(result,plan,r){if(validateBeatRealization(result,plan,r))return null;const physical=r.segments.map(x=>normalize(x.physical_text)),utterances=r.segments.filter(x=>x.utterance!==null).map(x=>normalize(x.utterance));if(new Set(physical).size!==physical.length||new Set(utterances).size!==utterances.length||utterances.length>physical.length)return null;const segments=r.segments.map(x=>({...x,physical_text:normalize(x.physical_text),utterance:x.utterance===null?null:normalize(x.utterance)})),narration=segments.map(x=>x.utterance===null?x.physical_text:`${x.physical_text} «${x.utterance}»`).join(' ');if(charLength(narration)<400||charLength(narration)>3500||!semanticGate(narration,plan))return null;return{...r,segments,narration}}

