import {EXCHANGE,LEGACY,MACRO,PERMISSIONS,PHASES,PREDICATES,PUBLIC_KEYS,SEMANTIC,SHA,UUID,VENDOR,WIRE} from './contracts.mjs';
import {canonical,exact,sha256} from './attestation.mjs';
const arr=Array.isArray,plain=x=>x&&typeof x==='object'&&!arr(x),uniq=a=>new Set(a).size===a.length;
const forbidden=x=>/test\s*room|private_constraints|declaration_text|asset_id/iu.test(JSON.stringify(x));
export const charLength=s=>[...s].length;
export const atomId=a=>a.declaration_ref;
export const predicateForFact=f=>PREDICATES[f.semantic_class];
export function validatePublicRequest(x){return !exact(x,PUBLIC_KEYS)||x.schema_version!==WIRE.request||!UUID.test(x.master_session_id)||!UUID.test(x.authority_receipt_id)||!UUID.test(x.request_key)||![...PHASES,...LEGACY,...EXCHANGE].includes(x.event_kind)?'REQUEST_INVALID':null}
function mediaOK(x){return exact(x,['media_id','asset_version','sha256','alt_text','crop'])&&UUID.test(x.media_id)&&Number.isInteger(x.asset_version)&&x.asset_version>0&&SHA.test(x.sha256)&&typeof x.alt_text==='string'&&x.alt_text.length>0&&x.crop===null}
function jsonSafe(x){if(!plain(x))return false;for(const [k,v] of Object.entries(x)){if(!/^[a-z][a-z0-9_]{0,63}$/u.test(k)||/private|secret|prompt|system|memory|continuity/iu.test(k))return false;if(plain(v)&&!jsonSafe(v))return false;if(arr(v)&&v.some(y=>plain(y)&&!jsonSafe(y)))return false}return true}
export function expectedUnits(surface){const units=[];for(const f of surface.fact_refs)units.push({seq:units.length+1,fact_ref:f.source_id,atom_id:null,predicate_id:predicateForFact(f),actor_key:null,persona_digest:null,dialogue_frame_id:null,dialogue_variant_id:null,addressee_scope:'party'});for(const a of [...surface.atoms].sort((x,y)=>x.ordinal-y.ordinal))units.push({seq:units.length+1,fact_ref:surface.fact_refs[0].source_id,atom_id:atomId(a),predicate_id:PREDICATES.atom,actor_key:null,persona_digest:null,dialogue_frame_id:null,dialogue_variant_id:null,addressee_scope:'party'});return units}
export async function validateClaimSurfaceBinding(claim,request,result){const e=claim?.envelope,s=result.projection;if(!e||e.master_session_id!==request.master_session_id||e.authority_receipt_id!==request.authority_receipt_id||e.renderer_version!==WIRE.renderer)return 'CLAIM_SURFACE_DRIFT';if(PHASES.includes(request.event_kind)||EXCHANGE.includes(request.event_kind)){const r=e.surface_projection_ref,isExchange=EXCHANGE.includes(request.event_kind);return e.schema_version!=='mission-narrative-dispatch-envelope/1.1'||(isExchange&&(e.event_kind!=='scontro_2v2'||e.exchange_event_kind!==request.event_kind))||(!isExchange&&e.event_kind!==request.event_kind)||r?.projection_id!==result.projection_id||r?.projection_sha256!==result.projection_sha256||r?.schema_version!==WIRE.surface||r?.mapping_version!==WIRE.mapping||!SHA.test(e.run_full_state_sha256)||!SHA.test(e.phase_claim_sha256)?'CLAIM_SURFACE_DRIFT':null}const f=s.fact_refs.find(x=>x.source_id===request.authority_receipt_id),b=e.legacy_surface_binding_ref;if(e.schema_version!=='mission-narrative-dispatch-envelope/1.0'||e.event_kind!==request.event_kind||!SHA.test(e.receipt_payload_sha256)||!SHA.test(e.narrative_sha256)||!plain(e.narrative_projection)||!f||f.semantic_class!=='mechanical_outcome'||s.phase!=='scontro_2v2'||!exact(b,['schema_version','surface_projection_id','surface_projection_sha256','receipt_payload_sha256','narrative_sha256','fact_digest','full_state_sha256','binding_sha256'])||b.schema_version!==VENDOR.legacy_binding_schema||b.surface_projection_id!==result.projection_id||b.surface_projection_sha256!==result.projection_sha256||b.receipt_payload_sha256!==e.receipt_payload_sha256||b.narrative_sha256!==e.narrative_sha256||b.fact_digest!==f.digest||!SHA.test(b.full_state_sha256)||!SHA.test(b.binding_sha256))return 'LEGACY_SURFACE_BINDING_MISSING';const tuple={master_session_id:request.master_session_id,authority_receipt_id:request.authority_receipt_id,event_kind:request.event_kind,receipt_payload_sha256:e.receipt_payload_sha256,narrative_projection:e.narrative_projection,narrative_sha256:e.narrative_sha256,fact_source_id:f.source_id,fact_digest:f.digest,surface_projection_id:result.projection_id,surface_projection_sha256:result.projection_sha256,full_state_sha256:b.full_state_sha256};return b.binding_sha256===await sha256(`${VENDOR.legacy_binding_schema}\n${canonical(tuple)}`)?null:'LEGACY_SURFACE_BINDING_DRIFT'}
export function validateSurfaceResult(w,request){
 if(!exact(w,['schema_version','projection_id','projection','projection_sha256','replayed','provider_calls','cost_usd'])||w.schema_version!=='mission-surface-project-result/1.0'||!UUID.test(w.projection_id)||!SHA.test(w.projection_sha256)||typeof w.replayed!=='boolean'||w.provider_calls!==0||w.cost_usd!==0)return 'SURFACE_WRAPPER';
 const expectedPhase=[...LEGACY,...EXCHANGE].includes(request.event_kind)?'scontro_2v2':request.event_kind,expectedMacro=request.event_kind==='combat_terminal'?'combat_terminal':[...LEGACY,...EXCHANGE].includes(request.event_kind)?'combat_round':MACRO[request.event_kind],s=w.projection;
 if(!exact(s,['schema_version','mapping_version','master_session_id','authority_receipt_id','phase','macro_phase','fact_refs','atoms','personas','media','dialogue','frame','permissions'])||s.schema_version!==WIRE.surface||s.mapping_version!==WIRE.mapping||s.master_session_id!==request.master_session_id||s.authority_receipt_id!==request.authority_receipt_id||s.phase!==expectedPhase||s.macro_phase!==expectedMacro)return 'SURFACE_INVALID';
 /* projection_sha256 e' autoritativo e pinzato dal claim R19. Non viene
    ricalcolato dopo JSON.parse: PostgreSQL conserva la scala JSONB 1.00. */
 if(!arr(s.fact_refs)||!s.fact_refs.length||!arr(s.atoms)||!arr(s.personas)||!arr(s.media)||!plain(s.dialogue)||!exact(s.dialogue,['source','source_digest','frames'])||!SHA.test(s.dialogue.source_digest)||!arr(s.dialogue.frames)||s.dialogue.frames.some(x=>!exact(x,['frame_id','variant_id'])||typeof x.frame_id!=='string'||typeof x.variant_id!=='string')||!plain(s.frame)||!exact(s.frame,['environment_source','environment_scope','source_digest','technical_location_visible'])||s.frame.technical_location_visible!==false||!SHA.test(s.frame.source_digest)||!exact(s.permissions,['may_decide_mechanics','may_voice_pg','may_reveal_hidden'])||Object.values(s.permissions).some(Boolean))return 'SURFACE_SHAPE';
 const facts=new Map;for(const f of s.fact_refs){if(!exact(f,['source_id','fact_code','semantic_class','permission','reveal','digest'])||!UUID.test(f.source_id)||typeof f.fact_code!=='string'||!SEMANTIC.includes(f.semantic_class)||!arr(f.permission)||!f.permission.length||!uniq(f.permission)||f.permission.some(x=>!PERMISSIONS.includes(x))||!exact(f.reveal,['authority','scope','phase','mode'])||f.reveal.authority!=='server_receipt'||f.reveal.scope!=='party'||f.reveal.phase!==s.phase||!['authorized','authorized_confirmation_only'].includes(f.reveal.mode)||!SHA.test(f.digest))return 'FACT_PERMISSION';facts.set(f.source_id,f)}if(facts.size!==s.fact_refs.length)return 'FACT_DUPLICATE';
 const atomKeys=['declaration_ref','actor_ref','target_ref','kind','intent','outcome','ordinal','source_version'],ids=[],ord=[];for(const a of s.atoms){if(!plain(a)||Object.keys(a).some(k=>!atomKeys.includes(k))||!UUID.test(a.declaration_ref)||!UUID.test(a.actor_ref)||(a.target_ref!==undefined&&!UUID.test(a.target_ref))||!Number.isInteger(a.ordinal)||a.ordinal<1||typeof a.kind!=='string'||!a.kind||!Number.isInteger(a.source_version)||a.source_version<1||!jsonSafe(a.intent)||!jsonSafe(a.outcome)||forbidden(a))return 'ATOM_INVALID';ids.push(a.declaration_ref);ord.push(a.ordinal)}if(!uniq(ids)||!uniq(ord))return 'ATOM_DUPLICATE';
 const actorKeys=[],personaDigests=[];for(const p of s.personas){if(!exact(p,['actor_key','template_id','template_version_id','persona','persona_digest','media_id'])||typeof p.actor_key!=='string'||!p.actor_key||!UUID.test(p.template_id)||!UUID.test(p.template_version_id)||!jsonSafe(p.persona)||!SHA.test(p.persona_digest)||!UUID.test(p.media_id))return 'PERSONA_INVALID';actorKeys.push(p.actor_key);personaDigests.push(p.persona_digest)}if(!uniq(actorKeys)||!uniq(personaDigests))return 'PERSONA_DUPLICATE';
 if(s.media.some(x=>!mediaOK(x))||s.personas.some(p=>!s.media.some(m=>m.media_id===p.media_id))||forbidden(s))return 'MEDIA_OR_LEAK_INVALID';return null
}
export function validatePlan(surface,result,p){if(!exact(p,['schema_version','projection_id','projection_sha256','phase','segments'])||p.schema_version!==WIRE.plan||p.projection_id!==result.projection_id||p.projection_sha256!==result.projection_sha256||p.phase!==surface.phase||!arr(p.segments))return 'PLAN_INVALID';const expected=expectedUnits(surface);if(p.segments.length!==expected.length)return 'PLAN_COVERAGE';for(let i=0;i<expected.length;i++)if(!exact(p.segments[i],Object.keys(expected[i]))||JSON.stringify(p.segments[i])!==JSON.stringify(expected[i]))return 'PLAN_BINDING';return null}
export function validateRealization(surface,result,r){if(!exact(r,['schema_version','projection_id','projection_sha256','phase','segments','narration'])||r.schema_version!==WIRE.realization||r.projection_id!==result.projection_id||r.projection_sha256!==result.projection_sha256||r.phase!==surface.phase||!arr(r.segments)||typeof r.narration!=='string'||charLength(r.narration)<400||charLength(r.narration)>3500)return 'REALIZATION_INVALID';const expected=expectedUnits(surface);if(r.segments.length!==expected.length)return 'REALIZATION_COVERAGE';for(let i=0;i<expected.length;i++){const x=r.segments[i],e=expected[i];if(!exact(x,[...Object.keys(e),'text'])||JSON.stringify(Object.fromEntries(Object.keys(e).map(k=>[k,x[k]])))!==JSON.stringify(e)||typeof x.text!=='string'||!x.text)return 'REALIZATION_BINDING'}return null}

/* Gate consumer per la tuple editoriale PACK004. La fonte ratificata resta
   immutata: questo controllo chiude il metadata boundary prima di qualunque
   renderer del pack. I fact non portano ordinal/source_version nel contratto
   PACK004; se il caller tenta di aggiungerli, la shape exact li respinge. */
export function validateEditorialTuple(c){
 if(!exact(c,['projection','persona','phase_id','frame_id','frame_variant_id','variant_id','permissions','fact_ref','declaration_ref','atom']))return 'EDITORIAL_CLAIM_SHAPE';
 const p=c.projection,persona=c.persona,f=c.fact_ref,d=c.declaration_ref,a=c.atom;
 if(!exact(p,['projection_id','projection_sha256','session_id','run_id','authority_id'])||!exact(persona,['projection_id','session_id','run_id','actor_key','actor_ref','persona_digest'])||!exact(f,['projection_id','session_id','run_id','actor_ref','source_id','fact_code','semantic_class','permission','reveal','digest']))return 'EDITORIAL_TUPLE_SHAPE';
 if(!UUID.test(p.projection_id)||!UUID.test(p.session_id)||!UUID.test(p.run_id)||!SHA.test(p.projection_sha256)||p.authority_id!=='surface_r16.server_attested'||!['kado','yori'].includes(persona.actor_key)||!UUID.test(persona.actor_ref)||!SHA.test(persona.persona_digest))return 'EDITORIAL_AUTHORITY';
 const same=x=>x.projection_id===p.projection_id&&x.session_id===p.session_id&&x.run_id===p.run_id;
 if(!same(persona)||!same(f)||f.actor_ref!==persona.actor_ref||!UUID.test(f.source_id)||!SHA.test(f.digest))return 'EDITORIAL_TUPLE_DRIFT';
 if(a===null||d===null){if(a!==null||d!==null)return 'EDITORIAL_PARTIAL_ATOM';return null}
 if(!exact(d,['projection_id','session_id','run_id','declaration_id','actor_ref','target_ref','digest'])||!exact(a,['projection_id','session_id','run_id','declaration_ref','actor_ref','target_ref','kind','intent','outcome','ordinal','source_version','digest']))return 'EDITORIAL_ATOM_SHAPE';
 if(!same(d)||!same(a)||!UUID.test(d.declaration_id)||!UUID.test(d.actor_ref)||!UUID.test(d.target_ref)||!SHA.test(d.digest)||!SHA.test(a.digest)||a.declaration_ref!==d.declaration_id||a.actor_ref!==d.actor_ref||a.target_ref!==d.target_ref||a.target_ref!==persona.actor_ref)return 'EDITORIAL_ATOM_DRIFT';
 if(!Number.isInteger(a.ordinal)||a.ordinal<1||!Number.isInteger(a.source_version)||a.source_version<1)return 'EDITORIAL_ATOM_METADATA';
 return null;
}

