import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {dirname} from 'node:path';
const root='/Users/antonello/Desktop/theuntoldstory';
const here=dirname(fileURLToPath(import.meta.url));
const base=readFileSync(root+'/sito_live/admin.html','utf8');
const html=readFileSync(here+'/admin.html','utf8');
const asset=readFileSync(here+'/mission-rapid-editor.asset.v1.mjs','utf8');
const count=(s,x)=>s.split(x).length-1;
const block=(s,a,z)=>s.slice(s.indexOf(a),s.indexOf(z)+z.length);
test('baseline admin riconciliata',()=>assert.equal(createHash('sha256').update(base).digest('hex'),'e080eca67975ac034643a1c7b5454106bdfb656613eeb85376831385bc2ac01a'));
test('un solo nav editor',()=>assert.equal(count(html,'id="mission-rapid-nav"'),1));
test('una sola pagina editor',()=>assert.equal(count(html,'id="mission-rapid-page"'),1));
test('un solo host editor',()=>assert.equal(count(html,'id="mission-rapid-host"'),1));
test('nav inizialmente nascosta',()=>assert.match(html,/id="mission-rapid-nav" hidden/));
test('pagina inizialmente nascosta',()=>assert.match(html,/id="mission-rapid-page" hidden/));
test('gate admin esplicito',()=>assert.match(html,/admin=nbeRole==='admin'/));
test('modulo importato una volta',()=>assert.equal(count(html,"import('./mission-rapid-editor.asset.v1.mjs')"),1));
test('picker mappe esistente importato',()=>assert.equal(count(html,"import('./MAPPE_UI_PICKER.asset.v3.mjs')"),1));
test('edge media unica riusata',()=>assert.match(html,/functions\.invoke\('png_media_attest_v1'/));
test('nessun upload storage diretto per PNG rapidi',()=>assert.doesNotMatch(block(html,'MISSION-RAPID-EDITOR JS INIZIO','MISSION-RAPID-EDITOR JS FINE'),/storage\.from/));
test('approvazione media server',()=>assert.match(html,/nb_admin_media_approve/));
test('digest file calcolato nel browser',()=>assert.match(html,/crypto\.subtle\.digest\('SHA-256'/));
test('request upload persistita sul File',()=>assert.match(html,/missionRapidMediaPending=new WeakMap/));
test('release media fissata',()=>assert.match(html,/mission-rapid-media\/2026-09-19\.1/));
test('ramo Scorta byte-identico',()=>assert.equal(block(html,'SCORTA-MEDIA-ADMIN JS INIZIO','SCORTA-MEDIA-ADMIN JS FINE'),block(base,'SCORTA-MEDIA-ADMIN JS INIZIO','SCORTA-MEDIA-ADMIN JS FINE')));
test('struttura bijuu non toccata',()=>assert.equal(count(html,'EMB_EXTRA'),count(base,'EMB_EXTRA')));
test('asset espone la factory',()=>assert.match(asset,/export function createMissionRapidEditor/));
test('asset invoca il compilatore Edge',()=>assert.match(asset,/functions\.invoke\('mission_authoring_ai'/));
test('asset ricorda il dispatch della request',()=>assert.match(asset,/compileDispatched/));
test('asset usa public_objective del contratto',()=>{assert.match(asset,/phase\.public_objective/);assert.doesNotMatch(asset,/phase\.objective_public/);});
test('asset rende grado e partecipanti modificabili',()=>{assert.match(asset,/Partecipanti minimi/);assert.match(asset,/meta\.grade/);});
test('asset rende identità e comportamento PNG',()=>{assert.match(asset,/\['Identità','identity'/);assert.match(asset,/\['Comportamento','behavior'/);});
test('asset rende conoscenze e limiti PNG',()=>{assert.match(asset,/Conoscenze riservate/);assert.match(asset,/\['Limiti','limits'/);});
test('asset rende le transizioni modificabili',()=>{assert.match(asset,/Risultato pubblico/);assert.match(asset,/transition\.to_step_key/);});
test('asset consente condizioni terminali senza SQL',()=>{assert.match(asset,/Aggiungi condizione/);assert.match(asset,/surrender_after_exchanges/);assert.match(asset,/reach_position/);});
test('asset non contiene segreti',()=>assert.doesNotMatch(asset,/SUPABASE_SERVICE_ROLE_KEY|eyJ[A-Za-z0-9_-]{20,}/));
test('pubblica dipende da preview seal',()=>assert.match(asset,/previewSeal.*canPublish|canPublish\(state\)/s));
