import assert from 'node:assert/strict';
import test from 'node:test';
import {applyCompiled, autoLinkMedia, buildDraftDocument, canPublish, createInitialState, dispatchCompiler, DRAFT_SCHEMA, invalidatePreview, localBlockingErrors, PREVIEW_SCHEMA, proposeApprovedBundle, VERSION} from './mission-rapid-editor.mjs';

const id = n => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const actor = (key, name = key) => ({actor_key: key, identity: {name}, team: 'civili', mechanical_request: {archetype_tags: [], combat_role: '', desired_grade: 'C'}});
const compiled = {mission: {title: 'Titolo'}, actors: [actor('mercante', 'Taro')], phases: [{step_key: 'inizio'}], terminal_rules: [], map_request: {mode: 'default10'}};
const validState = () => {
  const s = createInitialState({plot: 'Una trama sufficientemente lunga per superare ogni controllo locale.'});
  s.compiled = structuredClone(compiled); s.draftId = id(1); s.controlVersion = 3; s.configuration.gathering_location_id = id(2);
  s.configuration.actor_bindings = [{actor_key: 'mercante', base_bundle_id: id(3), media_id: id(4), team: 'civili', approved: true}];
  s.configuration.budget = {max_calls: 14, max_cost_usd: .15, max_input_tokens: 12000, max_output_tokens: 20000}; return s;
};

test('versione esplicita', () => assert.match(VERSION, /^mission-rapid-editor\//));
test('schema bozza esplicito', () => assert.equal(DRAFT_SCHEMA, 'mission-rapid-draft/1'));
test('stato iniziale usa default 10x10', () => assert.equal(createInitialState().configuration.map.mode, 'default10'));
test('stato iniziale non pubblicabile', () => assert.equal(canPublish(createInitialState()), false));
test('normalizza phase hints', () => assert.deepEqual(createInitialState({phase_hints: [' A ', '', 'B']}).source.phase_hints, ['A', 'B']));
test('source iniziale ha forma canonica completa', () => assert.deepEqual(createInitialState().source, {plot:'',phase_hints:[],png_uploads:[],has_map_image:false,map_notes:''}));
test('source normalizza upload e note mappa', () => assert.deepEqual(createInitialState({png_uploads:[{upload_key:' png_1 ',label:' Ren '}],map_notes:' Bosco '}).source.png_uploads, [{upload_key:'png_1',label:'Ren'}]));
test('match esatto actor key', () => assert.equal(autoLinkMedia([actor('guardia')], [{media_id: id(1), file_name: 'guardia.png'}]).linked.guardia.media_id, id(1)));
test('match nome pubblico', () => assert.equal(autoLinkMedia([actor('guardia', 'Ren Aoki')], [{media_id: id(1), file_name: 'ren-aoki.webp'}]).linked.guardia.media_id, id(1)));
test('match ignora accenti', () => assert.equal(autoLinkMedia([actor('medico', 'Sàkura')], [{media_id: id(1), file_name: 'sakura.jpg'}]).linked.medico.media_id, id(1)));
test('nessun match resta non assegnato', () => assert.equal(autoLinkMedia([actor('a')], [{media_id: id(1), file_name: 'ignoto.png'}]).unassigned.length, 1));
test('due upload per actor sono ambigui', () => assert.equal(autoLinkMedia([actor('guardia')], [{media_id: id(1), file_name: 'guardia.png'}, {media_id: id(2), file_name: 'guardia-ritratto.png'}]).ambiguous.length, 1));
test('pari merito tra actor non collega', () => assert.equal(Object.keys(autoLinkMedia([actor('a', 'Ren'), actor('b', 'Ren')], [{media_id: id(1), file_name: 'ren.png'}]).linked).length, 0));
test('documento mantiene schema', () => assert.equal(buildDraftDocument(validState()).schema_version, DRAFT_SCHEMA));
test('documento è una copia', () => { const s = validState(), d = buildDraftDocument(s); d.source.plot = 'x'; assert.notEqual(s.source.plot, 'x'); });
test('trama corta blocca', () => assert(localBlockingErrors(createInitialState({plot: 'breve'})).some(x => x.code === 'PLOT_REQUIRED')));
test('compilazione assente blocca', () => assert(localBlockingErrors(createInitialState({plot: 'x'.repeat(50)})).some(x => x.code === 'COMPILE_REQUIRED')));
test('binding assente blocca', () => { const s = validState(); s.configuration.actor_bindings = []; assert(localBlockingErrors(s).some(x => x.code === 'ACTOR_BINDING_MISSING')); });
test('bundle assente blocca', () => { const s = validState(); s.configuration.actor_bindings[0].base_bundle_id = ''; assert(localBlockingErrors(s).some(x => x.code === 'BUNDLE_REQUIRED')); });
test('media assente blocca', () => { const s = validState(); s.configuration.actor_bindings[0].media_id = ''; assert(localBlockingErrors(s).some(x => x.code === 'MEDIA_MISSING')); });
test('team non ammesso blocca', () => { const s = validState(); s.configuration.actor_bindings[0].team = 'altro'; assert(localBlockingErrors(s).some(x => x.code === 'TEAM_INVALID')); });
test('png non approvato blocca', () => { const s = validState(); s.configuration.actor_bindings[0].approved = false; assert(localBlockingErrors(s).some(x => x.code === 'PNG_UNAPPROVED')); });
test('location assente blocca', () => { const s = validState(); s.configuration.gathering_location_id = ''; assert(localBlockingErrors(s).some(x => x.code === 'LOCATION_REQUIRED')); });
test('mappa specifica senza template blocca', () => { const s = validState(); s.configuration.map.mode = 'specific'; assert(localBlockingErrors(s).some(x => x.code === 'MAP_SPEC_REQUIRED')); });
test('mappa specifica richiede spec della stessa versione', () => { const s=validState();s.configuration.map={mode:'specific',template_key:'mission_map_a',template_version:1,spec:{template_key:'mission_map_b'}};assert(localBlockingErrors(s).some(x=>x.code==='MAP_SPEC_REQUIRED')); });
test('budget assente blocca', () => { const s = validState(); s.configuration.budget = null; assert(localBlockingErrors(s).some(x => x.code === 'BUDGET_REQUIRED')); });
test('stato valido non ha errori locali', () => assert.deepEqual(localBlockingErrors(validState()), []));
test('vittoria non può produrre fallimento', () => { const s=validState();s.compiled.terminal_rules=[{rule_key:'r1',type:'victory',outcome:'failure'}];assert(localBlockingErrors(s).some(x=>x.code==='RULE_OUTCOME_INVALID')); });
test('fuga richiede soggetto', () => { const s=validState();s.compiled.terminal_rules=[{rule_key:'r1',type:'escape',outcome:'success',subject_key:null}];assert(localBlockingErrors(s).some(x=>x.code==='RULE_SUBJECT_REQUIRED')); });
test('sopravvivenza richiede soglia', () => { const s=validState();s.compiled.terminal_rules=[{rule_key:'r1',type:'survive_rounds',outcome:'success',threshold:null}];assert(localBlockingErrors(s).some(x=>x.code==='RULE_THRESHOLD_INVALID')); });
test('condizione richiede fase combat', () => { const s=validState();s.compiled.terminal_rules=[{rule_key:'r1',phase_key:'inizio',type:'victory',outcome:'success'}];assert(localBlockingErrors(s).some(x=>x.code==='RULE_PHASE_INVALID')); });
test('fuga richiede actor key noto', () => { const s=validState();s.compiled.phases[0].kind='combat';s.compiled.terminal_rules=[{rule_key:'r1',phase_key:'inizio',type:'escape',outcome:'failure',subject_key:'ignoto'}];assert(localBlockingErrors(s).some(x=>x.code==='RULE_ESCAPE_ACTOR_INVALID')); });
test('due condizioni native nella stessa fase bloccano', () => { const s=validState();s.compiled.phases[0].kind='combat';s.compiled.terminal_rules=[{rule_key:'r1',phase_key:'inizio',type:'survive_rounds',outcome:'success',threshold:2},{rule_key:'r2',phase_key:'inizio',type:'surrender_after_exchanges',outcome:'success',threshold:3}];assert(localBlockingErrors(s).some(x=>x.code==='RULE_NATIVE_AMBIGUOUS')); });
test('apply compiled accetta state server', () => { const s = createInitialState(); applyCompiled(s, {schema_version: 'mission-rapid-compile-state/1', draft_id: id(1), control_version: 2, compiled}); assert.equal(s.compiled.actors[0].actor_key, 'mercante'); });
test('apply compiled prepara binding', () => { const s = createInitialState(); applyCompiled(s, {schema_version: 'mission-rapid-compile-result/1', draft_id: id(1), control_version: 2, compiled}); assert.equal(s.configuration.actor_bindings.length, 1); });
test('apply compiled adotta source canonica server', () => { const s=createInitialState({plot:'vecchia trama lunga abbastanza per il controllo'});const source={plot:'trama canonica server lunga abbastanza per il controllo',phase_hints:[],png_uploads:[],has_map_image:false,map_notes:''};applyCompiled(s,{schema_version:'mission-rapid-compile-result/1',draft_id:id(1),control_version:2,source,compiled});assert.deepEqual(s.source,source); });
test('documento include correzioni editoriali', () => { const s=validState();s.compiled.mission.title='Titolo corretto';s.compiled.phases[0].title='Fase corretta';assert.equal(buildDraftDocument(s).compiled.mission.title,'Titolo corretto');assert.equal(buildDraftDocument(s).compiled.phases[0].title,'Fase corretta'); });
test('apply compiled rifiuta schema', () => assert.throws(() => applyCompiled(createInitialState(), {schema_version: 'x'})));
test('preview verde abilita publish', () => { const s = validState(); s.preview = {schema_version: PREVIEW_SCHEMA, errors: [], draft_version: 3}; s.previewSeal = 'a'.repeat(64); s.dirty = false; assert.equal(canPublish(s), true); });
test('preview con errori non abilita publish', () => { const s = validState(); s.preview = {schema_version: PREVIEW_SCHEMA, errors: [{code: 'X'}], draft_version: 3}; s.previewSeal = 'a'.repeat(64); s.dirty = false; assert.equal(canPublish(s), false); });
test('preview di versione vecchia non abilita publish', () => { const s = validState(); s.preview = {schema_version: PREVIEW_SCHEMA, errors: [], draft_version: 2}; s.previewSeal = 'a'.repeat(64); s.dirty = false; assert.equal(canPublish(s), false); });
test('seal malformato non abilita publish', () => { const s = validState(); s.preview = {schema_version: PREVIEW_SCHEMA, errors: [], draft_version: 3}; s.previewSeal = 'x'; s.dirty = false; assert.equal(canPublish(s), false); });
test('busy non abilita publish', () => { const s = validState(); s.preview = {schema_version: PREVIEW_SCHEMA, errors: [], draft_version: 3}; s.previewSeal = 'a'.repeat(64); s.dirty = false; s.busy = true; assert.equal(canPublish(s), false); });
test('invalidate cancella seal e preview', () => { const s = validState(); s.preview = {}; s.previewSeal = 'a'; invalidatePreview(s); assert.equal(s.preview, null); assert.equal(s.previewSeal, null); assert.equal(s.dirty, true); });
test('dispatch usa una sola Edge nominata', async () => { let calls=0; const out=await dispatchCompiler({functions:{invoke:async(name,args)=>{calls++;assert.equal(name,'mission_authoring_ai');assert.deepEqual(args,{body:{request_key:id(9)}});return{data:{schema_version:'mission-rapid-compile-result/1'}};}}},id(9)); assert.equal(calls,1); assert.equal(out.confirmed,true); });
test('dispatch conserva errore incerto per polling', async () => { const error={message:'network'}; const out=await dispatchCompiler({functions:{invoke:async()=>({error})}},id(9)); assert.equal(out.confirmed,false); assert.equal(out.error,error); });
test('dispatch rifiuta request non UUID', async () => await assert.rejects(dispatchCompiler({functions:{invoke:async()=>({})}},'x')));
test('dispatch rifiuta client senza Edge', async () => await assert.rejects(dispatchCompiler({},id(9))));
test('proposta bundle usa grado e precedenti approvati', () => { const a=actor('guardia');a.mechanical_request.archetype_tags=['guardia'];const bundles=[{bundle_id:id(3),display_name:'Guardia Genin',mechanics:{document:{skeleton:{identity:{role:'guardia'}}}},mechanical_profile:{rank:'Genin',archetype:'difensore',abilities:[]}},{bundle_id:id(4),display_name:'Medico Genin',mechanics:{document:{skeleton:{identity:{role:'medico'}}}},mechanical_profile:{rank:'Genin',archetype:'supporto',abilities:[]}}];assert.equal(proposeApprovedBundle(a,bundles).bundle_id,id(3)); });
test('proposta bundle non decide un pari merito', () => { const a=actor('ignoto');const bundles=[{bundle_id:id(3),display_name:'Uno',mechanical_profile:{rank:'Genin',archetype:'x',abilities:[]}},{bundle_id:id(4),display_name:'Due',mechanical_profile:{rank:'Genin',archetype:'y',abilities:[]}}];assert.equal(proposeApprovedBundle(a,bundles),null); });
test('apply compiled precompila schieramento e bundle proposto', () => { const s=createInitialState();const c=structuredClone(compiled);c.actors[0].role='guardia';c.actors[0].mechanical_request.archetype_tags=['guardia'];const catalog={bundles:[{bundle_id:id(3),display_name:'Guardia Genin',mechanics:{document:{skeleton:{identity:{role:'guardia'}}}},mechanical_profile:{rank:'Genin',archetype:'difensore',abilities:[]}}]};applyCompiled(s,{schema_version:'mission-rapid-compile-result/1',draft_id:id(1),control_version:2,compiled:c},catalog);assert.equal(s.configuration.actor_bindings[0].base_bundle_id,id(3));assert.equal(s.configuration.actor_bindings[0].team,'civili'); });
