import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {Script,createContext} from 'node:vm';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
const dir=path.dirname(fileURLToPath(import.meta.url)),sha=b=>createHash('sha256').update(b).digest('hex');
const html=fs.readFileSync(path.join(dir,'LAND.html'),'utf8');
let syntax=0;
for(const match of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)){
 if(/\bsrc\s*=|application\/ld\+json|application\/json/i.test(match[1]))continue;
 new Script(match[2]);syntax++;
}
const match=html.match(/<script id="common-panel-bundle">([\s\S]*?)<\/script>/);assert.ok(match);
const anchor='window.TUSCommonPanel=module0;';assert.equal(match[1].split(anchor).length,2);
const context=createContext({window:{},structuredClone,crypto:{randomUUID},queueMicrotask});
new Script(match[1].replace(anchor,anchor+'window.feedbackQA={createPanelController:module2.createPanelController,mountPanelSurface:module1.mountPanelSurface,mountPanelView:module5.mountPanelView};')).runInContext(context);
const {createPanelController,mountPanelSurface,mountPanelView}=context.window.feedbackQA;
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const clone=x=>JSON.parse(JSON.stringify(x));
class Element{constructor(tag,doc){this.tagName=tag;this.ownerDocument=doc;this.children=[];this.attributes={};this.style={};this.hidden=false;this.listeners={};this.textContent='';}append(n){this.children.push(n);}replaceChildren(...n){this.children=n;}setAttribute(k,v){this.attributes[k]=v;}getAttribute(k){return this.attributes[k]??null;}addEventListener(k,f){this.listeners[k]=f;}contains(n){return this===n||this.children.some(x=>x.contains(n));}querySelectorAll(){return [];}focus(){}}
function dom(){const doc={activeElement:null,createElement(tag){return new Element(tag,doc);}};return new Element('div',doc);}
const text=n=>[n.textContent,...n.children.map(text)].join(' ');
const nodes=n=>[n,...n.children.flatMap(nodes)];
function fixture(){
 let version=1,mode='ready',behavior='reject',principal=id(4),counter=9;const calls=[];
 const offer=()=>({offer_id:id(8),kind:'action',operation:'declare',actor_id:id(3),label:'Scelta autorizzata',context_version:version,scene_version:null,requires_role:false,choices:[{group_id:id(10),label:'Opzione',selection_mode:'single',purpose:'generic',min_selected:1,max_selected:1,depends_on:null,options:[{option_id:id(11),label:'Opzione disponibile',distance_m:null,direction:null}]}],input_fields:[]});
 function envelope(options=false){const blocked=mode==='blocked';return {schema_version:'combat-panel/1',status:blocked?'blocked':'ready',reason_code:blocked?'not_available':null,context:blocked?null:{activity_id:id(2),activity_kind:'ordinary_v2',location_id:id(1),round_id:null,round_no:null,phase:'action',phase_label:'Azione',version,scene_version:null,policy_id:'test',simulated:true},viewer:{command_actor_id:blocked?null:id(3),controlled_actors:blocked?[]:[{actor_id:id(3),label:'PG sintetico'}],is_master:false,is_admin:false,can_command:!blocked},actors:blocked?[]:[{actor_id:id(3),kind:'pg',body_only:false,display_name:'PG sintetico',team:null,state:'active',mine:true,action_due:true,defense_due:false,resources:null,distance_from_viewer_m:null}],offers:blocked?[]:options?[offer()]:[],map:null,movement_explanations:null,companion:null,sabaku_transport:null,multiplication:null,narrative:null,receipt:null,round_details:null};}
 async function rpc(name,args){calls.push({name,args:clone(args)});if(name!=='combat_panel_commit_v1')return envelope(name==='combat_panel_options_v1');const cmd=args.p_command;if(behavior==='uncertain')throw Error('untrusted transport detail');if(behavior==='reject')return {schema_version:'combat-panel-error/1',status:'rejected',request_key:cmd.request_key,code:'selection_rejected',message:'La scelta non è più disponibile.',recovery:'refresh'};const e=envelope();e.receipt={receipt_id:id(50),request_key:cmd.request_key,operation:'declare',replayed:false,activity_id:id(2),round_id:null,context_version_before:cmd.context_version,context_version_after:version,declaration_id:null,report_id:null,values_written:false,display_events:[]};return e;}
 const controller=createPanelController({rpc,contextKey:()=>principal,locationId:id(1),requestKey:()=>id(counter++)});
 async function select(){assert.equal(await controller.readState(),true);assert.equal(await controller.readOptions(),true);controller.selectOffer(id(8));controller.selectOption(id(10),id(11),true);}
 return {controller,select,rpc,calls,envelope,setVersion:v=>version=v,setMode:v=>mode=v,setBehavior:v=>behavior=v,setPrincipal:v=>principal=v};
}
const cases=[
 ['G1_rifiuto_refresh_persistente',async()=>{const f=fixture(),c=f.controller;await f.select();await c.submit();const key=c.snapshot().lastCommand.request_key;await c.readState();await c.readOptions();assert.equal(c.snapshot().lastCommand.status,'rejected');assert.equal(c.snapshot().lastCommand.request_key,key);assert.equal(c.snapshot().rejection.code,'selection_rejected');assert.equal(c.snapshot().canPrepare,false);const root=dom();mountPanelView(root).render(c.snapshot());assert.ok(text(root).includes('La scelta non è più disponibile.'));assert.ok(!text(root).includes(key));assert.equal(f.calls.filter(x=>x.name==='combat_panel_commit_v1').length,1);}],
 ['G2_versione_invalida_scelte_non_esito',async()=>{const f=fixture(),c=f.controller;await f.select();await c.submit();await c.readState();await c.readOptions();c.selectOffer(id(8));c.selectOption(id(10),id(11),true);f.setVersion(2);await c.readState();assert.equal(c.snapshot().selectedOfferId,null);assert.equal(c.snapshot().selectedOptionIds.length,0);assert.equal(c.snapshot().optionsReady,false);assert.equal(c.snapshot().lastCommand.status,'rejected');c.invalidate();assert.equal(c.snapshot().lastCommand.status,'rejected');assert.equal(c.snapshot().envelope,null);await c.readState();assert.equal(c.snapshot().canPrepare,false);assert.equal(c.snapshot().lastCommand.status,'rejected');f.setPrincipal(id(90));await c.readState();assert.equal(c.snapshot().lastCommand,null);}],
 ['G3_conferma_successiva_sostituisce_esito',async()=>{const f=fixture(),c=f.controller;await f.select();await c.submit();const old=c.snapshot().lastCommand.request_key;f.setBehavior('success');await f.select();assert.ok(await c.submit());assert.equal(c.snapshot().rejection,null);assert.equal(c.snapshot().lastCommand.status,'confirmed');assert.notEqual(c.snapshot().lastCommand.request_key,old);await c.readState();assert.equal(c.snapshot().lastCommand.status,'confirmed');const root=dom();mountPanelView(root).render(c.snapshot());assert.ok(text(root).includes('Richiesta confermata dal server'));assert.ok(!text(root).includes('La scelta non è più disponibile.'));}],
 ['G4_incertezza_retry_identico',async()=>{const f=fixture(),c=f.controller;await f.select();f.setBehavior('uncertain');await c.submit();const first=clone(f.calls.at(-1).args.p_command);assert.equal(c.snapshot().pending,true);f.setMode('blocked');await c.readState();assert.equal(c.snapshot().pending,true);c.invalidate();assert.equal(c.snapshot().lastCommand.request_key,first.request_key);assert.equal(f.calls.filter(x=>x.name==='combat_panel_commit_v1').length,1);f.setMode('ready');f.setVersion(2);await c.readState();f.setBehavior('success');await c.retry();const sent=f.calls.filter(x=>x.name==='combat_panel_commit_v1');assert.equal(sent.length,2);assert.deepEqual(sent[1].args.p_command,first);assert.equal(c.snapshot().pending,false);}],
 ['G5_errore_preinvio_visibile_sicuro',async()=>{const f=fixture(),root=dom();const surface=mountPanelSurface({root,client:{rpc:async(n,a)=>({data:await f.rpc(n,a),error:null})},locationId:id(1),contextKey:()=>id(4)});await surface.open();await surface.submit();assert.ok(text(root).includes('Completa le scelte richieste'));assert.equal(f.calls.filter(x=>x.name==='combat_panel_commit_v1').length,0);await surface.setNarrative(42);assert.ok(text(root).includes('Il testo non può essere modificato'));assert.ok(!text(root).includes('narrative_unavailable'));f.controller.reportInteractionError(Error('raw_private_diagnostic_fixture'));const other=dom();mountPanelView(other).render(f.controller.snapshot());assert.ok(!text(other).includes('raw_private_diagnostic_fixture'));assert.ok(text(other).includes('La scelta non può essere inviata.'));surface.dispose();}],
 ['G6_blocked_feedback_senza_comandi',async()=>{const f=fixture(),c=f.controller;await f.select();await c.submit();f.setMode('blocked');await c.readState();const root=dom();mountPanelView(root).render(c.snapshot());assert.ok(text(root).includes('La scelta non è più disponibile.'));assert.ok(!text(root).includes(c.snapshot().lastCommand.request_key));assert.ok(text(root).includes('Scontro non disponibile'));assert.equal(nodes(root).filter(x=>['select','input','textarea'].includes(x.tagName)).length,0);assert.deepEqual(nodes(root).filter(x=>x.tagName==='button').map(x=>x.textContent),['Rileggi lo stato']);assert.equal(c.snapshot().canPrepare,false);}]
];
const start=performance.now(),results=[];
for(const [id,run]of cases){try{await run();results.push({id,status:'PASS'});}catch(e){results.push({id,status:'FAIL',reason:e instanceof Error?e.message:String(e)});}}
const files=['LAND.html','BUILD.py','BASELINE.json','PLAN.md','VERIFY.mjs',...['controller.mjs','mount.mjs','view.mjs','validate.mjs','multiplication.mjs','map.mjs','domain-views.mjs'].map(n=>'ui/'+n)];
const result={task_id:'LAND-COMMAND-FEEDBACK-CANDIDATE-001',state:results.every(x=>x.status==='PASS')?'COMPONENT_PASS':'COMPONENT_FAIL',created_at_utc:new Date().toISOString(),groups:6,passed:results.filter(x=>x.status==='PASS').length,results,elapsed_ms:performance.now()-start,syntax_inline_scripts:syntax,inputs:Object.fromEntries(files.map(n=>[n,sha(fs.readFileSync(path.join(dir,n)))])),limits:{SQL:0,Docker:0,provider:0,browser:0,API:0,dom:'minimal synthetic fixture',tested:'actual Common bundle exported only in VM harness',privateUI003:'not modified or executed',cause_assalto010:'not established'},retries:0};
fs.writeFileSync(path.join(dir,'QA_RESULT.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));if(result.state!=='COMPONENT_PASS')process.exitCode=1;
