import assert from 'node:assert/strict';
import test from 'node:test';
import {inspectRaster, isMissingObject, MAX_BYTES, rapidHeaders, RAPID_RELEASE, validTicket} from './runtime.mjs';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const headers=extra=>new Headers({'x-mr-draft-id':id(1),'x-mr-actor-key':'guardia','x-mr-bundle-id':id(2),'x-mr-request-key':id(3),'x-mr-sha256':'a'.repeat(64),'x-mr-expected-release':RAPID_RELEASE,'content-type':'image/png',...extra});
const png=(w=3,h=4)=>{const b=new Uint8Array(24);b.set([137,80,78,71,13,10,26,10]);b[16]=(w>>>24)&255;b[17]=(w>>>16)&255;b[18]=(w>>>8)&255;b[19]=w&255;b[20]=(h>>>24)&255;b[21]=(h>>>16)&255;b[22]=(h>>>8)&255;b[23]=h&255;return b;};
test('release separata e finita',()=>assert.match(RAPID_RELEASE,/^mission-rapid-media\//));
test('limite cinque MB',()=>assert.equal(MAX_BYTES,5242880));
test('png legge dimensioni',()=>assert.deepEqual(inspectRaster(png(33,44),'image/png'),{mime:'image/png',width:33,height:44,bytes:24}));
test('mime dichiarato deve coincidere',()=>assert.throws(()=>inspectRaster(png(),'image/jpeg')));
test('file vuoto rifiutato',()=>assert.throws(()=>inspectRaster(new Uint8Array(),'image/png')));
test('dimensione oltre 8192 rifiutata',()=>assert.throws(()=>inspectRaster(png(9000,4),'image/png')));
test('header validi',()=>assert.equal(rapidHeaders(headers()).actor_key,'guardia'));
test('draft uuid obbligatorio',()=>assert.throws(()=>rapidHeaders(headers({'x-mr-draft-id':'x'}))));
test('actor key stabile',()=>assert.throws(()=>rapidHeaders(headers({'x-mr-actor-key':'Guardia 1'}))));
test('bundle uuid obbligatorio',()=>assert.throws(()=>rapidHeaders(headers({'x-mr-bundle-id':'x'}))));
test('request uuid obbligatoria',()=>assert.throws(()=>rapidHeaders(headers({'x-mr-request-key':'x'}))));
test('sha obbligatorio',()=>assert.throws(()=>rapidHeaders(headers({'x-mr-sha256':'a'}))));
test('release esatta',()=>assert.throws(()=>rapidHeaders(headers({'x-mr-expected-release':'old'}))));
test('mime limitato',()=>assert.throws(()=>rapidHeaders(headers({'content-type':'image/gif'}))));
test('ticket coerente',()=>assert.equal(validTicket({schema_version:'mission-rapid-media-ticket/1',request_key:id(3),template_version_id:id(4),bucket:'avatars',object_path:'ninja-book/test_png/r1/assets/mr_00000000000040008000000000000003_v1.png'},rapidHeaders(headers())).bucket,'avatars'));
test('ticket request drift rifiutato',()=>assert.throws(()=>validTicket({schema_version:'mission-rapid-media-ticket/1',request_key:id(8),template_version_id:id(4),bucket:'avatars',object_path:'ninja-book/test_png/r1/assets/mr_00000000000040008000000000000003_v1.png'},rapidHeaders(headers()))));
test('ticket bucket rifiutato',()=>assert.throws(()=>validTicket({schema_version:'mission-rapid-media-ticket/1',request_key:id(3),template_version_id:id(4),bucket:'x',object_path:'ninja-book/test_png/r1/assets/mr_00000000000040008000000000000003_v1.png'},rapidHeaders(headers()))));
test('ticket path rifiutato',()=>assert.throws(()=>validTicket({schema_version:'mission-rapid-media-ticket/1',request_key:id(3),template_version_id:id(4),bucket:'avatars',object_path:'../x.png'},rapidHeaders(headers()))));
test('NoSuchKey Storage 400 equivale a oggetto assente',()=>assert.equal(isMissingObject(400,{code:'NoSuchKey',error:'not_found',httpStatusCode:404}),true));
test('not_found Storage 400 equivale a oggetto assente',()=>assert.equal(isMissingObject(400,{statusCode:'404',error:'not_found'}),true));
test('altri 400 Storage restano bloccanti',()=>assert.equal(isMissingObject(400,{error:'invalid_request'}),false));
