'use strict';
(async function(){
  var started=Date.now(), results=[], c=TUSBackground.compile;
  function check(x,message){if(!x)throw Error(message);}
  function run(name,fn){try{fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',reason:e.message});}}
  function noActive(s){check(!/<(?:script|iframe|object|embed|form|input|svg|math|style|meta|link|base)\b|\son[a-z]+\s*=|\shref\s*=|\ssrcset\s*=|\sid\s*=|\sname\s*=/i.test(s),'markup attivo o attributi vietati rimasti');}
  run('01 testo semplice e ritorni a capo',()=>{var x=c('Uno < due\nTre & quattro',false);check(!x.error&&x.html.includes('Uno &lt; due\nTre &amp; quattro'),'testo alterato');check(x.srcdoc.includes('white-space:pre-wrap'),'a capo assenti');});
  run('02 formattazione consentita',()=>{var x=c('<h2>Titolo</h2><p><b>Forte</b> <em>Corsivo</em></p><ul><li>Voce</li></ul>',false);check(!x.error&&x.html.includes('<h2>')&&x.html.includes('<li>'),'tag consentiti persi');});
  run('03 struttura Shion sanitizzata',()=>{var x=c(SHION_FIXTURE,false);check(!x.error,'esempio rifiutato');noActive(x.html);check(!x.html.includes('max-height:0')&&!x.html.includes('class=')&&!x.html.includes('opacity'),'contenuti nascosti');check(x.html.includes('Testo del personaggio'),'storia perduta');check(x.images===1&&!/<img/.test(x.html),'immagine non protetta');});
  run('04 sezioni native espandibili',()=>{var x=c('<details><summary>Origini</summary><p>Storia</p></details>',false);check(x.html.includes('<details>')&&x.html.includes('<summary>Origini</summary>'),'details persi');});
  run('05 script ed eventi',()=>{var x=c('<script>parent.__PWNED=1</script><img src=x onerror="parent.__PWNED=1"><p onclick="alert(1)">Testo</p>',false);noActive(x.html);check(x.html.includes('Testo'),'testo perduto');});
  run('06 HTML malformato e mXSS',()=>{var x=c('<math><mtext><table><mglyph><style><!--</style><img title="--><img src=x onerror=alert(1)>"><p>Fine</p>',false);check(!x.error,'parser non gestito');noActive(x.html);});
  run('07 SVG MathML e URL attivi',()=>{var x=c('<svg><a href="javascript:alert(1)">X</a></svg><math><mi>x</mi></math><a href="data:text/html,x">Link</a><img src="javascript:alert(1)">',true);noActive(x.html);check(!x.html.includes('javascript:')&&!x.html.includes('data:'),'protocollo attivo');});
  run('08 CSS di copertura e occultamento',()=>{var x=c('<style>body{display:none}</style><div id=x class=x hidden style="position:fixed;z-index:99999;opacity:0;display:none;max-height:0;color:#7c2413;text-align:center;font-size:20px;background:url(/probe)">Visibile</div>',false);noActive(x.html);check(!/position|opacity|display|z-index|max-height|url\(/.test(x.html),'CSS vietato');check(x.html.includes('color:#7c2413')&&x.html.includes('Visibile'),'CSS sicuro o testo perduto');});
  run('09 moduli navigazione e popup',()=>{var x=c('<meta http-equiv="refresh" content="0;url=/probe"><base href="/probe"><form action="/probe"><input name=password><button formaction="/probe">Invia</button></form><a href="https://example.com" target="_top" ping="/probe" download>Apri</a>',false);noActive(x.html);check(!/formaction|target=|ping=|download/.test(x.html),'navigazione attiva');});
  run('10 domini immagini e credenziali',()=>{['http://i.imgur.com/a.png','//i.imgur.com/a.png','https://i.imgur.com.evil.test/a.png','https://u:p@i.imgur.com/a.png','https://i.imgur.com/a.svg','https://i.imgur.com/a.png?x=1','https://i.imgur.com:444/a.png','data:image/png;base64,AA','/relative.png'].forEach(u=>{var x=c('<img src="'+u+'">',true);check(x.images===0&&!/<img/.test(x.html),'URL accettato: '+u);});});
  run('11 immagine consentita dopo consenso',()=>{var x=c('<img src="https://i.postimg.cc/QdX5wF47/konoha-suiton.png" onload="alert(1)">',true);check(x.images===1&&x.html.includes('crossorigin="anonymous"')&&x.html.includes('referrerpolicy="no-referrer"'),'protezioni immagine assenti');noActive(x.html);});
  run('12 CSP isolamento e rete prima del consenso',()=>{var x=c('<img src="https://i.postimg.cc/QdX5wF47/konoha-suiton.png"><iframe src="/probe"></iframe><img src="/probe">',false);check(x.srcdoc.includes("default-src 'none'")&&x.srcdoc.includes("script-src 'none'")&&x.srcdoc.includes("img-src 'none'"),'CSP aperta');check(!/<img|<iframe/.test(x.html),'risorsa attiva prima del consenso');check(x.srcdoc.indexOf('Content-Security-Policy')<x.srcdoc.indexOf('<body>'),'CSP tardiva');});
  run('13 lunghezza e ripiego',()=>{check(!!c('x'.repeat(50001),false).error,'limite caratteri non applicato');check(!c('x'.repeat(50000),false).error,'confine valido rifiutato');});
  run('14 elementi e profondità',()=>{check(!!c('<p>x</p>'.repeat(1001),false).error,'limite elementi');check(!!c('<div>'.repeat(31)+'x'+'</div>'.repeat(31),false).error,'limite profondità');check(!c('<div>'.repeat(30)+'x'+'</div>'.repeat(30),false).error,'confine profondità');});
  run('15 limite immagini',()=>{check(!!c('<img alt=x>'.repeat(9),false).error,'limite immagini');check(!c('<img alt=x>'.repeat(8),false).error,'confine immagini');});
  var source=document.getElementById('source'),host=document.getElementById('reader');source.value=SHION_FIXTURE;
  var reader=TUSBackground.mount(source,host);reader.setEditable(true);
  run('16 proprietario lettore sorgente e sandbox',()=>{var original=source.value;reader.setEditable(false);check(source.hidden,'sorgente non nascosto in lettura');check(host.querySelector('iframe').getAttribute('sandbox')==='','permessi sandbox');reader.setEditable(true);check(!source.hidden&&source.value===original,'sorgente modificato');check(host.querySelector('iframe').referrerPolicy==='no-referrer','referrer iframe');});
  document.getElementById('view-reader').onclick=()=>reader.setEditable(false);
  document.getElementById('view-editor').onclick=()=>reader.setEditable(true);
  var report={revision:'r2',cases:results,passed:results.filter(x=>x.status==='PASS').length,total:16,elapsed_ms:Date.now()-started,db_writes:0,provider_calls:0,ai_tokens:0,limits:'16 casi / 20 minuti'};
  document.getElementById('results').textContent=JSON.stringify(report,null,2);
  // Deposito locale delle sole evidenze sintetiche, nessuna informazione del PG.
  var request=new XMLHttpRequest();request.open('POST','/report');request.setRequestHeader('Content-Type','application/json');request.send(JSON.stringify(report));
})();
