BEGIN;
SET LOCAL lock_timeout='3s';
SET LOCAL statement_timeout='15s';
DO $pre$ BEGIN
PERFORM pg_advisory_xact_lock(hashtextextended('C1241-source-ui-release',611));
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('combat_consumer_private.staff_test_allowed(uuid,uuid[],boolean)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres}","oid":43060,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"255e8d73cdd7c3814132d71f0f45b1b5","signature":"combat_consumer_private.staff_test_allowed(uuid,uuid[],boolean)","source_md5":"6c865d07f0cb55b7d1f1a14a3f6e12b6","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'combat_consumer_private.staff_test_allowed(uuid,uuid[],boolean)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('master_v2_is_master(uuid)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres,service_role=X/postgres}","oid":31303,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"adff2e39542883bce427976b2df27896","signature":"master_v2_is_master(uuid)","source_md5":"a850d9bf449b3644e72012e9135b3598","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'master_v2_is_master(uuid)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_ai_board_owner.staff_only()')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres}","oid":40974,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"005295a0e0bbd57100039b2cb6b85b66","signature":"mission_ai_board_owner.staff_only()","source_md5":"e9eb8c959bad86a2a4b265ca0e4800a0","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_ai_board_owner.staff_only()'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_creation_editor_v1(uuid,uuid)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres,authenticated=X/postgres}","oid":50683,"owner":"postgres","config":["search_path=\"\""],"signature":"mission_creation_editor_v1(uuid,uuid)","source_md5":"fc3cefd739ef59a597609abaf21ef130","security_definer":true,"ddl_md5":"d162e5ebcfe925a4d534a887089c59d0"}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_creation_editor_v1(uuid,uuid)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_creation_owner.map_binding_guard_mission_publish_v1(jsonb,jsonb)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres}","oid":56207,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"9e829441cd5a3aeccf1ef19166d254ce","signature":"mission_creation_owner.map_binding_guard_mission_publish_v1(jsonb,jsonb)","source_md5":"f60cf1a6e80cce62400b272a4d421149","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_creation_owner.map_binding_guard_mission_publish_v1(jsonb,jsonb)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_creation_owner.preflight_document_v2(jsonb)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres}","oid":56835,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"6608c503e941afc8af377f0551f83a90","signature":"mission_creation_owner.preflight_document_v2(jsonb)","source_md5":"fd43774c85507142c0459611779c78a0","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_creation_owner.preflight_document_v2(jsonb)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_creation_owner.save_complete(uuid,uuid,text,bigint,jsonb)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres}","oid":50679,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"fbce7d725c950c2eca2234f797b339ad","signature":"mission_creation_owner.save_complete(uuid,uuid,text,bigint,jsonb)","source_md5":"0f5c8c882acf4f10031845c9086fa6b9","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_creation_owner.save_complete(uuid,uuid,text,bigint,jsonb)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_creation_owner.validate_document(jsonb)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres}","oid":50677,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"570fc0c99743036f6f2d54c7ce539b25","signature":"mission_creation_owner.validate_document(jsonb)","source_md5":"98e4f2eca325cf2f33fad277b90c0533","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_creation_owner.validate_document(jsonb)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_generic_owner.mission_editor_snapshot(uuid)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres}","oid":50072,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"fcfa5e11298dec73618e634b91db143e","signature":"mission_generic_owner.mission_editor_snapshot(uuid)","source_md5":"f75066897c92cdc3311d699b32430115","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_generic_owner.mission_editor_snapshot(uuid)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_human_staff_source_create_v1(uuid,jsonb,uuid)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres,authenticated=X/postgres}","oid":300864,"owner":"postgres","config":["search_path=\"\""],"signature":"mission_human_staff_source_create_v1(uuid,jsonb,uuid)","source_md5":"edc4d0a02979a49a87a014e53a10dfca","security_definer":true,"ddl_md5":"f43c302a9ef55f6794ecf94139585c74"}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_human_staff_source_create_v1(uuid,jsonb,uuid)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_human_staff_test_start_v1(uuid,uuid,uuid[],uuid)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres,authenticated=X/postgres}","oid":50735,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"48ae61fc9250ac6ccd97e858db882296","signature":"mission_human_staff_test_start_v1(uuid,uuid,uuid[],uuid)","source_md5":"ac289854f74768b8fdd293916d14b59b","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_human_staff_test_start_v1(uuid,uuid,uuid[],uuid)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_internal.fingerprint(jsonb)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres}","oid":33975,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"c2aa3985fcc7063f430d637bad02a0db","signature":"mission_internal.fingerprint(jsonb)","source_md5":"d150375c42b2487d0a85834bc83b1c66","security_definer":false}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_internal.fingerprint(jsonb)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('missione_crea(text,text,text,text,text,integer,integer,text,integer,integer)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres,service_role=X/postgres,authenticated=X/postgres}","oid":19355,"owner":"postgres","config":["search_path=public"],"ddl_md5":"a55beeefa7793a48ad957ba2755ba725","signature":"missione_crea(text,text,text,text,text,integer,integer,text,integer,integer)","source_md5":"cbb8fb183841f4d5901119ca4d73b8bf","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'missione_crea(text,text,text,text,text,integer,integer,text,integer,integer)'; END IF;
IF (SELECT jsonb_build_object('table',c.oid::regclass::text,'oid',c.oid::bigint,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'columns_md5',(SELECT md5(jsonb_agg(jsonb_build_array(a.attnum,a.attname,a.atttypid,a.atttypmod,a.attnotnull,a.attidentity,a.attgenerated) ORDER BY a.attnum)::text) FROM pg_attribute a WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped),'constraints_md5',(SELECT md5(coalesce(jsonb_agg(jsonb_build_array(x.conname,x.contype,pg_get_constraintdef(x.oid)) ORDER BY x.conname),'[]'::jsonb)::text) FROM pg_constraint x WHERE x.conrelid=c.oid)) FROM pg_class c WHERE c.oid=to_regclass('locations')) IS DISTINCT FROM $pin${"acl":"{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}","oid":18074,"owner":"postgres","table":"locations","columns_md5":"1b28daf2c39a33a4ccb0c634853a7e5a","constraints_md5":"c416703d6772c05953a6e5fa38919183"}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_TABLE_DRIFT:%', 'locations'; END IF;
IF (SELECT jsonb_build_object('table',c.oid::regclass::text,'oid',c.oid::bigint,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'columns_md5',(SELECT md5(jsonb_agg(jsonb_build_array(a.attnum,a.attname,a.atttypid,a.atttypmod,a.attnotnull,a.attidentity,a.attgenerated) ORDER BY a.attnum)::text) FROM pg_attribute a WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped),'constraints_md5',(SELECT md5(coalesce(jsonb_agg(jsonb_build_array(x.conname,x.contype,pg_get_constraintdef(x.oid)) ORDER BY x.conname),'[]'::jsonb)::text) FROM pg_constraint x WHERE x.conrelid=c.oid)) FROM pg_class c WHERE c.oid=to_regclass('mission_creation_owner.h3_staff_source_requests')) IS DISTINCT FROM $pin${"acl":"{postgres=arwdDxtm/postgres}","oid":300847,"owner":"postgres","table":"mission_creation_owner.h3_staff_source_requests","columns_md5":"9b711768879f932f7c0723bb98682514","constraints_md5":"415f69e8ce8447c312741caf74b077f8"}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_TABLE_DRIFT:%', 'mission_creation_owner.h3_staff_source_requests'; END IF;
IF (SELECT jsonb_build_object('table',c.oid::regclass::text,'oid',c.oid::bigint,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'columns_md5',(SELECT md5(jsonb_agg(jsonb_build_array(a.attnum,a.attname,a.atttypid,a.atttypmod,a.attnotnull,a.attidentity,a.attgenerated) ORDER BY a.attnum)::text) FROM pg_attribute a WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped),'constraints_md5',(SELECT md5(coalesce(jsonb_agg(jsonb_build_array(x.conname,x.contype,pg_get_constraintdef(x.oid)) ORDER BY x.conname),'[]'::jsonb)::text) FROM pg_constraint x WHERE x.conrelid=c.oid)) FROM pg_class c WHERE c.oid=to_regclass('mission_creation_owner.requests')) IS DISTINCT FROM $pin${"acl":"{postgres=arwdDxtm/postgres}","oid":50588,"owner":"postgres","table":"mission_creation_owner.requests","columns_md5":"8141ab077bef77edf0f0f136eef6e2e2","constraints_md5":"12bd65b0dea56ed8d8f278e158208d49"}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_TABLE_DRIFT:%', 'mission_creation_owner.requests'; END IF;
IF (SELECT jsonb_build_object('table',c.oid::regclass::text,'oid',c.oid::bigint,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'columns_md5',(SELECT md5(jsonb_agg(jsonb_build_array(a.attnum,a.attname,a.atttypid,a.atttypmod,a.attnotnull,a.attidentity,a.attgenerated) ORDER BY a.attnum)::text) FROM pg_attribute a WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped),'constraints_md5',(SELECT md5(coalesce(jsonb_agg(jsonb_build_array(x.conname,x.contype,pg_get_constraintdef(x.oid)) ORDER BY x.conname),'[]'::jsonb)::text) FROM pg_constraint x WHERE x.conrelid=c.oid)) FROM pg_class c WHERE c.oid=to_regclass('missions')) IS DISTINCT FROM $pin${"acl":"{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}","oid":19307,"owner":"postgres","table":"missions","columns_md5":"8100b0cde8d8eca765bc526c7e512525","constraints_md5":"590eea7192adab49a6d40486e65071a2"}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_TABLE_DRIFT:%', 'missions'; END IF;
IF EXISTS(SELECT 1 FROM public.master_v2_sessions WHERE location_id='0b85f354-9cdb-47e1-baf9-3d266bb7e06b' AND closed_at IS NULL) OR EXISTS(SELECT 1 FROM public.combat_v2_sessions WHERE location_id='0b85f354-9cdb-47e1-baf9-3d266bb7e06b' AND closed_at IS NULL) THEN RAISE EXCEPTION 'C1241_STAFF_BUSY'; END IF;
END $pre$;
CREATE OR REPLACE FUNCTION public.mission_human_staff_source_create_v1(p_request uuid, p_document jsonb, p_location uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE old record;pf jsonb;validation jsonb;m jsonb;
 mid uuid;doc_sha text;result jsonb;scene jsonb;enc jsonb;actor jsonb;enc_count integer:=0;
BEGIN
 IF auth.uid() IS NULL OR auth.role() IS DISTINCT FROM 'authenticated' OR p_request IS NULL
 OR p_location IS DISTINCT FROM '0b85f354-9cdb-47e1-baf9-3d266bb7e06b'::uuid
 THEN RAISE EXCEPTION 'H3_STAFF_SOURCE_AUTHORITY' USING ERRCODE='42501'; END IF;
 PERFORM mission_ai_board_owner.staff_only();
 PERFORM 1 FROM public.locations WHERE id=p_location AND is_active AND is_test FOR SHARE;
 IF NOT FOUND OR NOT public.master_v2_is_master(auth.uid())
 OR combat_consumer_private.staff_test_allowed(p_location,ARRAY[auth.uid()],false) IS DISTINCT FROM true
 THEN RAISE EXCEPTION 'H3_STAFF_SOURCE_AUTHORITY' USING ERRCODE='42501'; END IF;
 doc_sha:=mission_internal.fingerprint(p_document);
 PERFORM pg_advisory_xact_lock(hashtextextended('mission-create:'||p_request::text,611));
 SELECT * INTO old FROM mission_creation_owner.h3_staff_source_requests WHERE request_key=p_request;
 IF FOUND THEN
  IF old.actor_user IS DISTINCT FROM auth.uid() OR old.document_sha256 IS DISTINCT FROM doc_sha
  THEN RAISE EXCEPTION 'H3_STAFF_SOURCE_REPLAY_CONFLICT' USING ERRCODE='40001'; END IF;
  RETURN old.result;
 END IF;
 IF EXISTS(SELECT 1 FROM mission_creation_owner.requests WHERE request_key=p_request)
 THEN RAISE EXCEPTION 'H3_STAFF_SOURCE_REQUEST_CONFLICT' USING ERRCODE='40001'; END IF;
 pf:=mission_creation_owner.preflight_document_v2(p_document);
 IF (pf->>'ok')::boolean IS DISTINCT FROM true
 THEN RAISE EXCEPTION 'H3_STAFF_SOURCE_PREFLIGHT:%',pf->'errors' USING ERRCODE='22023'; END IF;
 m:=p_document->'mission';
 IF m->>'direction_mode' IS DISTINCT FROM 'human' OR m->>'team_min' IS DISTINCT FROM '1'
 OR m->>'team_max' IS DISTINCT FROM '1' OR p_document#>>'{plan,base_plan_version_id}' IS NOT NULL
 THEN RAISE EXCEPTION 'H3_STAFF_SOURCE_SCOPE' USING ERRCODE='22023'; END IF;
 FOR scene IN SELECT value FROM jsonb_array_elements(p_document#>'{plan,definition,scenes}') LOOP
  FOR enc IN SELECT value FROM jsonb_array_elements(coalesce(scene->'encounters','[]'::jsonb)) LOOP
   enc_count:=enc_count+1;
   IF (jsonb_array_length(enc->'actors') BETWEEN 1 AND 4) IS NOT TRUE
   THEN RAISE EXCEPTION 'H4_STAFF_SOURCE_PNG_COUNT' USING ERRCODE='22023'; END IF;
   IF EXISTS(SELECT 1 FROM jsonb_array_elements(enc->'actors') a WHERE nullif(a->>'actor_key','') IS NULL)
    OR (SELECT count(DISTINCT a->>'actor_key') FROM jsonb_array_elements(enc->'actors') a) <> jsonb_array_length(enc->'actors')
   THEN RAISE EXCEPTION 'H4_STAFF_SOURCE_DISTINCT_ACTORS' USING ERRCODE='22023'; END IF;
   FOR actor IN SELECT value FROM jsonb_array_elements(enc->'actors') LOOP
    IF actor->>'mechanical_binding_id' IS DISTINCT FROM '66a6628d-d465-4103-b74b-2184f4b07d04'
    THEN RAISE EXCEPTION 'H3_STAFF_SOURCE_APPROVED_PROFILE_REQUIRED' USING ERRCODE='42501'; END IF;
   END LOOP;
  END LOOP;
 END LOOP;
 IF enc_count<>1 THEN RAISE EXCEPTION 'H3_STAFF_SOURCE_ONE_ENCOUNTER' USING ERRCODE='22023'; END IF;
 validation:=mission_creation_owner.map_binding_guard_mission_publish_v1(p_document,mission_creation_owner.validate_document(p_document));
 mid:=public.missione_crea(m->>'title',m->>'grado',m->>'briefing',nullif(m->>'village',''),m->>'tag_trama',1,1,validation->>'gathering_name',30,0);
 -- La stessa transazione non espone mai la fonte aperta alla bacheca o alle iscrizioni.
 UPDATE public.missions SET status='annullata' WHERE id=mid AND status='aperta';
 IF NOT FOUND THEN RAISE EXCEPTION 'H3_STAFF_SOURCE_RESERVATION_FAILED'; END IF;
 result:=mission_creation_owner.save_complete(mid,p_request,mission_internal.fingerprint(mission_generic_owner.mission_editor_snapshot(mid)),0,p_document);
 IF result->>'schema_version' IS DISTINCT FROM 'mission-creation-result/1'
 OR result->>'mission_id' IS DISTINCT FROM mid::text OR result->>'state' IS DISTINCT FROM 'configured'
 OR NOT EXISTS(SELECT 1 FROM public.missions WHERE id=mid AND status='annullata' AND xp_reward=30 AND ryo_reward=0)
 THEN RAISE EXCEPTION 'H3_STAFF_SOURCE_POSTCONDITION'; END IF;
 INSERT INTO mission_creation_owner.h3_staff_source_requests(request_key,actor_user,document_sha256,mission_id,result)
 VALUES(p_request,auth.uid(),doc_sha,mid,result);
 RETURN result;
END $function$
;
CREATE OR REPLACE FUNCTION public.mission_creation_editor_v1(p_mission uuid, p_plan_version uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare r mission_creation_owner.revisions;mid jsonb;vid uuid;
begin
 perform mission_ai_board_owner.staff_only();
 mid:=mission_generic_owner.mission_editor_snapshot(p_mission);
 if mid is null then raise exception 'MC_MISSION_NOT_FOUND' using errcode='22023';end if;
 vid:=coalesce(p_plan_version,(select plan_version_id from mission_generic_owner.plan_selections where mission_id=p_mission));
 if p_plan_version is not null and not exists(select 1 from public.mission_plan_versions v join public.mission_plans p on p.id=v.plan_id where v.id=vid and p.mission_id=p_mission)
 then raise exception 'MC_PLAN_SCOPE' using errcode='42501';end if;
 select * into r from mission_creation_owner.revisions where plan_version_id=vid and mission_id=p_mission;
 if found and r.document_sha256<>mission_internal.fingerprint(r.document) then raise exception 'MC_DOCUMENT_DRIFT' using errcode='40001';end if;
 return jsonb_build_object('schema_version','mission-creation-editor/1','mission',coalesce(r.document->'mission',mid||jsonb_build_object('direction_mode','human','gathering_location_id',null)),
 'editorial',coalesce(r.document->'editorial',jsonb_build_object('plot_private','','setting',jsonb_build_object('name','','description',''),'scenes','[]'::jsonb)),
 'arenas',coalesce(r.document->'arenas','[]'::jsonb),'plan_version_id',vid,'configured',r.plan_version_id is not null);
end $function$;
GRANT EXECUTE ON FUNCTION public.mission_human_staff_source_create_v1(uuid,jsonb,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mission_creation_editor_v1(uuid,uuid) TO authenticated;
DO $post$ BEGIN
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('combat_consumer_private.staff_test_allowed(uuid,uuid[],boolean)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres}","oid":43060,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"255e8d73cdd7c3814132d71f0f45b1b5","signature":"combat_consumer_private.staff_test_allowed(uuid,uuid[],boolean)","source_md5":"6c865d07f0cb55b7d1f1a14a3f6e12b6","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'combat_consumer_private.staff_test_allowed(uuid,uuid[],boolean)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('master_v2_is_master(uuid)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres,service_role=X/postgres}","oid":31303,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"adff2e39542883bce427976b2df27896","signature":"master_v2_is_master(uuid)","source_md5":"a850d9bf449b3644e72012e9135b3598","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'master_v2_is_master(uuid)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_ai_board_owner.staff_only()')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres}","oid":40974,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"005295a0e0bbd57100039b2cb6b85b66","signature":"mission_ai_board_owner.staff_only()","source_md5":"e9eb8c959bad86a2a4b265ca0e4800a0","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_ai_board_owner.staff_only()'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_creation_editor_v1(uuid,uuid)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres,authenticated=X/postgres}","oid":50683,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"c8fae66aa56d02b658dcb29105db9b8a","signature":"mission_creation_editor_v1(uuid,uuid)","source_md5":"962af693ff03fda37ff2bddfddd4d94d","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_creation_editor_v1(uuid,uuid)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_creation_owner.map_binding_guard_mission_publish_v1(jsonb,jsonb)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres}","oid":56207,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"9e829441cd5a3aeccf1ef19166d254ce","signature":"mission_creation_owner.map_binding_guard_mission_publish_v1(jsonb,jsonb)","source_md5":"f60cf1a6e80cce62400b272a4d421149","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_creation_owner.map_binding_guard_mission_publish_v1(jsonb,jsonb)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_creation_owner.preflight_document_v2(jsonb)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres}","oid":56835,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"6608c503e941afc8af377f0551f83a90","signature":"mission_creation_owner.preflight_document_v2(jsonb)","source_md5":"fd43774c85507142c0459611779c78a0","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_creation_owner.preflight_document_v2(jsonb)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_creation_owner.save_complete(uuid,uuid,text,bigint,jsonb)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres}","oid":50679,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"fbce7d725c950c2eca2234f797b339ad","signature":"mission_creation_owner.save_complete(uuid,uuid,text,bigint,jsonb)","source_md5":"0f5c8c882acf4f10031845c9086fa6b9","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_creation_owner.save_complete(uuid,uuid,text,bigint,jsonb)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_creation_owner.validate_document(jsonb)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres}","oid":50677,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"570fc0c99743036f6f2d54c7ce539b25","signature":"mission_creation_owner.validate_document(jsonb)","source_md5":"98e4f2eca325cf2f33fad277b90c0533","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_creation_owner.validate_document(jsonb)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_generic_owner.mission_editor_snapshot(uuid)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres}","oid":50072,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"fcfa5e11298dec73618e634b91db143e","signature":"mission_generic_owner.mission_editor_snapshot(uuid)","source_md5":"f75066897c92cdc3311d699b32430115","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_generic_owner.mission_editor_snapshot(uuid)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_human_staff_source_create_v1(uuid,jsonb,uuid)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres,authenticated=X/postgres}","oid":300864,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"f17166eea7f4655c7bdf90b1e9362beb","signature":"mission_human_staff_source_create_v1(uuid,jsonb,uuid)","source_md5":"6ec31bbf6f7dcc93285a772c74056284","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_human_staff_source_create_v1(uuid,jsonb,uuid)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_human_staff_test_start_v1(uuid,uuid,uuid[],uuid)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres,authenticated=X/postgres}","oid":50735,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"48ae61fc9250ac6ccd97e858db882296","signature":"mission_human_staff_test_start_v1(uuid,uuid,uuid[],uuid)","source_md5":"ac289854f74768b8fdd293916d14b59b","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_human_staff_test_start_v1(uuid,uuid,uuid[],uuid)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('mission_internal.fingerprint(jsonb)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres}","oid":33975,"owner":"postgres","config":["search_path=\"\""],"ddl_md5":"c2aa3985fcc7063f430d637bad02a0db","signature":"mission_internal.fingerprint(jsonb)","source_md5":"d150375c42b2487d0a85834bc83b1c66","security_definer":false}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'mission_internal.fingerprint(jsonb)'; END IF;
IF (SELECT jsonb_build_object('signature',p.oid::regprocedure::text,'oid',p.oid::bigint,'source_md5',md5(p.prosrc),'ddl_md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'config',p.proconfig) FROM pg_proc p WHERE p.oid=to_regprocedure('missione_crea(text,text,text,text,text,integer,integer,text,integer,integer)')) IS DISTINCT FROM $pin${"acl":"{postgres=X/postgres,service_role=X/postgres,authenticated=X/postgres}","oid":19355,"owner":"postgres","config":["search_path=public"],"ddl_md5":"a55beeefa7793a48ad957ba2755ba725","signature":"missione_crea(text,text,text,text,text,integer,integer,text,integer,integer)","source_md5":"cbb8fb183841f4d5901119ca4d73b8bf","security_definer":true}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_FUNCTION_DRIFT:%', 'missione_crea(text,text,text,text,text,integer,integer,text,integer,integer)'; END IF;
IF (SELECT jsonb_build_object('table',c.oid::regclass::text,'oid',c.oid::bigint,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'columns_md5',(SELECT md5(jsonb_agg(jsonb_build_array(a.attnum,a.attname,a.atttypid,a.atttypmod,a.attnotnull,a.attidentity,a.attgenerated) ORDER BY a.attnum)::text) FROM pg_attribute a WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped),'constraints_md5',(SELECT md5(coalesce(jsonb_agg(jsonb_build_array(x.conname,x.contype,pg_get_constraintdef(x.oid)) ORDER BY x.conname),'[]'::jsonb)::text) FROM pg_constraint x WHERE x.conrelid=c.oid)) FROM pg_class c WHERE c.oid=to_regclass('locations')) IS DISTINCT FROM $pin${"acl":"{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}","oid":18074,"owner":"postgres","table":"locations","columns_md5":"1b28daf2c39a33a4ccb0c634853a7e5a","constraints_md5":"c416703d6772c05953a6e5fa38919183"}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_TABLE_DRIFT:%', 'locations'; END IF;
IF (SELECT jsonb_build_object('table',c.oid::regclass::text,'oid',c.oid::bigint,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'columns_md5',(SELECT md5(jsonb_agg(jsonb_build_array(a.attnum,a.attname,a.atttypid,a.atttypmod,a.attnotnull,a.attidentity,a.attgenerated) ORDER BY a.attnum)::text) FROM pg_attribute a WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped),'constraints_md5',(SELECT md5(coalesce(jsonb_agg(jsonb_build_array(x.conname,x.contype,pg_get_constraintdef(x.oid)) ORDER BY x.conname),'[]'::jsonb)::text) FROM pg_constraint x WHERE x.conrelid=c.oid)) FROM pg_class c WHERE c.oid=to_regclass('mission_creation_owner.h3_staff_source_requests')) IS DISTINCT FROM $pin${"acl":"{postgres=arwdDxtm/postgres}","oid":300847,"owner":"postgres","table":"mission_creation_owner.h3_staff_source_requests","columns_md5":"9b711768879f932f7c0723bb98682514","constraints_md5":"415f69e8ce8447c312741caf74b077f8"}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_TABLE_DRIFT:%', 'mission_creation_owner.h3_staff_source_requests'; END IF;
IF (SELECT jsonb_build_object('table',c.oid::regclass::text,'oid',c.oid::bigint,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'columns_md5',(SELECT md5(jsonb_agg(jsonb_build_array(a.attnum,a.attname,a.atttypid,a.atttypmod,a.attnotnull,a.attidentity,a.attgenerated) ORDER BY a.attnum)::text) FROM pg_attribute a WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped),'constraints_md5',(SELECT md5(coalesce(jsonb_agg(jsonb_build_array(x.conname,x.contype,pg_get_constraintdef(x.oid)) ORDER BY x.conname),'[]'::jsonb)::text) FROM pg_constraint x WHERE x.conrelid=c.oid)) FROM pg_class c WHERE c.oid=to_regclass('mission_creation_owner.requests')) IS DISTINCT FROM $pin${"acl":"{postgres=arwdDxtm/postgres}","oid":50588,"owner":"postgres","table":"mission_creation_owner.requests","columns_md5":"8141ab077bef77edf0f0f136eef6e2e2","constraints_md5":"12bd65b0dea56ed8d8f278e158208d49"}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_TABLE_DRIFT:%', 'mission_creation_owner.requests'; END IF;
IF (SELECT jsonb_build_object('table',c.oid::regclass::text,'oid',c.oid::bigint,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'columns_md5',(SELECT md5(jsonb_agg(jsonb_build_array(a.attnum,a.attname,a.atttypid,a.atttypmod,a.attnotnull,a.attidentity,a.attgenerated) ORDER BY a.attnum)::text) FROM pg_attribute a WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped),'constraints_md5',(SELECT md5(coalesce(jsonb_agg(jsonb_build_array(x.conname,x.contype,pg_get_constraintdef(x.oid)) ORDER BY x.conname),'[]'::jsonb)::text) FROM pg_constraint x WHERE x.conrelid=c.oid)) FROM pg_class c WHERE c.oid=to_regclass('missions')) IS DISTINCT FROM $pin${"acl":"{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}","oid":19307,"owner":"postgres","table":"missions","columns_md5":"8100b0cde8d8eca765bc526c7e512525","constraints_md5":"590eea7192adab49a6d40486e65071a2"}$pin$::jsonb THEN RAISE EXCEPTION 'C1241_TABLE_DRIFT:%', 'missions'; END IF;
END $post$;
COMMIT;
